insert into public.gear_products (
  brand,
  model,
  name_ja,
  category_id,
  subcategory_id,
  weight_grams,
  official_weight_grams,
  measured_weight_grams,
  msrp_jpy,
  size,
  volume,
  color,
  material,
  capacity,
  official_url,
  image_url,
  released_at,
  discontinued,
  msrp_source_url,
  last_verified_at,
  verification_status
)
select
  'SOTO',
  v.model,
  v.name_ja,
  c.id,
  s.id,
  v.official_weight_grams,
  v.official_weight_grams,
  null,
  v.msrp_jpy,
  v.size,
  null,
  null,
  v.material,
  v.capacity,
  v.official_url,
  v.image_url,
  null,
  false,
  v.msrp_source_url,
  date '2026-06-05',
  'verified'
from (
  values
    ('ST-331', 'TrekMaster（トレックマスター）', 'stove', 195, 12870, '幅500×奥行140×高さ105mm（使用時・ホース含む） / 幅90×奥行70×高さ105mm（収納時・ホース含む）', null, null, 'https://soto.shinfuji.co.jp/products/st-331/', 'https://soto.shinfuji.co.jp/wp-content/uploads/products/ST-331_01.webp', 'https://soto.shinfuji.co.jp/products/st-331/'),
    ('ST-711', 'CB TOUGH 125', 'fuel', 220, 440, '直径65×高さ120mm（キャップ含む）', null, '125g', 'https://soto.shinfuji.co.jp/products/st-711/', 'https://soto.shinfuji.co.jp/wp-content/uploads/products/ST-711_0111.jpg', 'https://soto.shinfuji.co.jp/products/st-711/'),
    ('ST-712', 'CB TOUGH 220', 'fuel', 334, 495, '直径65×高さ186mm（キャップ含む）', null, '220g', 'https://soto.shinfuji.co.jp/products/st-712/', 'https://soto.shinfuji.co.jp/wp-content/uploads/products/ST-712_011.jpg', 'https://soto.shinfuji.co.jp/products/st-712/'),
    ('SOD-710T', 'パワーガス105トリプルミックス', 'fuel', 192, 682, '直径90×高さ65mm', null, '105g', 'https://soto.shinfuji.co.jp/products/sod-710t/', 'https://soto.shinfuji.co.jp/wp-content/uploads/products/SOD-710T_01-1.jpg', 'https://soto.shinfuji.co.jp/products/sod-710t/'),
    ('SOD-725T', 'パワーガス250トリプルミックス', 'fuel', 385, 792, '直径110×高さ90mm', null, '230g', 'https://soto.shinfuji.co.jp/products/sod-725t/', 'https://soto.shinfuji.co.jp/wp-content/uploads/products/SOD-725T_01-1.jpg', 'https://soto.shinfuji.co.jp/products/sod-725t/'),
    ('SOD-750T', 'パワーガス500トリプルミックス', 'fuel', 680, 1320, '直径110×高さ150mm', null, '460g', 'https://soto.shinfuji.co.jp/products/sod-750t/', 'https://soto.shinfuji.co.jp/wp-content/uploads/products/SOD-750T_01-1.jpg', 'https://soto.shinfuji.co.jp/products/sod-750t/'),
    ('SOD-523', 'スチームライスクッカー ITADAKI(イタダキ)', 'cookware', 250, 7480, '（使用時）φ108（鍋底φ96.6）×高さ155mm / （収納時）φ108（鍋底φ96.6）×高さ134mm', 'マグ350：ステンレス、マグ650：アルミニウム、リッド：PP、スペーサー：PP、リフター：アルミニウム、メッシュ収納袋：ポリエステル', 'マグ350：350ml（満水容量400ml） / マグ650：650ml（満水容量700ml）', 'https://soto.shinfuji.co.jp/products/sod-523/', 'https://soto.shinfuji.co.jp/wp-content/uploads/products/SOD-320_01-2.jpg', 'https://soto.shinfuji.co.jp/products/sod-523/'),
    ('ST-3108', 'ミニマルクッカー角', 'cookware', 375, 5775, '幅147×奥行147×高さ80mm', '鍋本体・フタ：アルミニウム / リフター：ステンレス', '800ml（満水容量約1,100ml）', 'https://soto.shinfuji.co.jp/products/st-3108/', 'https://soto.shinfuji.co.jp/wp-content/uploads/products/ST-3108_01-1.jpg', 'https://soto.shinfuji.co.jp/products/st-3108/'),
    ('ST-950', 'ステンレスヘビーポット GORA(ゴーラ)', 'cookware', 3500, 19800, '20cmポット、16cmポット、14cmポット、リッド、リフターのセット', 'ポット・リッド：ステンレス / リフター：アルミニウム / 収納袋：綿', '2,500ml / 1,200ml / 900ml', 'https://soto.shinfuji.co.jp/products/st-950/', 'https://soto.shinfuji.co.jp/wp-content/uploads/products/ST-950_01-1.jpg', 'https://soto.shinfuji.co.jp/products/st-950/'),
    ('ST-950P', 'GORA パンチングザル', 'cookware', 196, 3520, '直径195×高さ76mm', 'ステンレス', null, 'https://soto.shinfuji.co.jp/products/st-950p/', 'https://soto.shinfuji.co.jp/wp-content/uploads/products/ST-950P_01-1.jpg', 'https://soto.shinfuji.co.jp/products/st-950p/'),
    ('ST-950FP22', 'GORA フライパン22cm', 'cookware', 855, 2970, '直径240×高さ52mm', '鉄（シリコンクリア塗装）', null, 'https://soto.shinfuji.co.jp/products/st-950fp22/', 'https://soto.shinfuji.co.jp/wp-content/uploads/products/ST-950FP22_01-1.jpg', 'https://soto.shinfuji.co.jp/products/st-950fp22/'),
    ('ST-950FP16', 'GORA フライパン16cm', 'cookware', 433, 2090, '直径180×高さ37mm', '鉄（シリコンクリア塗装）', null, 'https://soto.shinfuji.co.jp/products/st-950fp16/', 'https://soto.shinfuji.co.jp/wp-content/uploads/products/ST-950FP16_01-1.jpg', 'https://soto.shinfuji.co.jp/products/st-950fp16/')
) as v(model, name_ja, subcategory_en, official_weight_grams, msrp_jpy, size, material, capacity, official_url, image_url, msrp_source_url)
join public.gear_categories c on c.name_en = 'cooking'
join public.gear_subcategories s on s.category_id = c.id and s.name_en = v.subcategory_en
on conflict (brand, model) do update
set name_ja = excluded.name_ja,
    category_id = excluded.category_id,
    subcategory_id = excluded.subcategory_id,
    weight_grams = excluded.weight_grams,
    official_weight_grams = excluded.official_weight_grams,
    measured_weight_grams = excluded.measured_weight_grams,
    msrp_jpy = excluded.msrp_jpy,
    size = excluded.size,
    volume = excluded.volume,
    color = excluded.color,
    material = excluded.material,
    capacity = excluded.capacity,
    official_url = excluded.official_url,
    image_url = excluded.image_url,
    released_at = excluded.released_at,
    discontinued = excluded.discontinued,
    msrp_source_url = excluded.msrp_source_url,
    last_verified_at = excluded.last_verified_at,
    verification_status = excluded.verification_status;
