alter table public.mountain_foundation_profiles
  drop constraint if exists mountain_foundation_profiles_region_check;

alter table public.mountain_foundation_profiles
  drop constraint if exists mountain_foundation_profiles_primary_region_check;

alter table public.mountain_foundation_profiles
  add constraint mountain_foundation_profiles_region_check
  check (region in ('HOKKAIDO', 'TOHOKU', 'HOKUSHINETSU', 'KANTO', 'HOKURIKU', 'TOKAI', 'KINKI', 'FUJI', 'OKUCHICHIBU', 'TANZAWA', 'NIKKO', 'YATSUGATAKE', 'NORTHERN_ALPS', 'CENTRAL_ALPS', 'SOUTHERN_ALPS', 'CHUGOKU', 'SHIKOKU', 'KYUSHU', 'YAKUSHIMA', 'KANTO_TOKYO', 'KANTO_TOKYO_SAITAMA_YAMANASHI', 'NORTHERN_ALPS_NAGANO', 'NORTHERN_ALPS_NAGANO_GIFU', 'JOSHU'));

alter table public.mountain_foundation_profiles
  add constraint mountain_foundation_profiles_primary_region_check
  check (primary_region in ('HOKKAIDO', 'TOHOKU', 'HOKUSHINETSU', 'KANTO', 'HOKURIKU', 'TOKAI', 'KINKI', 'FUJI', 'OKUCHICHIBU', 'TANZAWA', 'NIKKO', 'YATSUGATAKE', 'NORTHERN_ALPS', 'CENTRAL_ALPS', 'SOUTHERN_ALPS', 'CHUGOKU', 'SHIKOKU', 'KYUSHU', 'YAKUSHIMA', 'KANTO_TOKYO', 'JOSHU'));

update public.mountain_foundation_profiles
set supported_styles = array['DAY_HIKE', 'OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[]
where slug = 'tsubakuro-dake';

update public.mountain_foundation_profiles
set hut_support = 'FULL_SERVICE',
    tent_site_availability = 'DESIGNATED',
    alpine_environment = 'HIGH_ALPINE_EXPOSED'
where slug = 'jonen-dake';

update public.mountain_foundation_profiles
set hut_support = 'FULL_SERVICE',
    tent_site_availability = 'DESIGNATED',
    alpine_environment = 'HIGH_ALPINE_EXPOSED'
where slug = 'cho-gatake';

update public.mountain_foundation_profiles
set snow_or_ice_risk = 'SEASONAL_PATCHES'
where slug = 'shirouma-dake';

insert into public.mountain_foundation_profiles (
  slug,
  name_ja,
  region,
  primary_region,
  mountain_range,
  prefectures,
  elevation_m,
  is_hyakumeizan,
  supported_seasons,
  supported_styles,
  trip_profile,
  typical_required_systems,
  route_seriousness,
  technical_terrain,
  helmet_guidance,
  water_availability,
  hut_support,
  tent_site_availability,
  alpine_environment,
  snow_or_ice_risk,
  route_duration_band,
  escape_options,
  cell_signal_reliability,
  bear_or_wildlife_risk,
  volcanic_risk,
  season_opening_window
)
values
  ('tomuraushi-yama', 'トムラウシ山', 'HOKKAIDO', 'HOKKAIDO', '大雪山系', array['北海道']::text[], 2141, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'NATURAL_RELIABLE', 'BASIC_NO_BEDDING', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'REMOTE', 'POOR', 'HIGH', 'NONE', 'SUMMER_AUTUMN'),
  ('tokachi-dake', '十勝岳', 'HOKKAIDO', 'HOKKAIDO', '十勝岳連峰', array['北海道']::text[], 2077, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'RECOMMENDED', 'LIMITED_OR_SEASONAL', 'EMERGENCY_ONLY', 'NONE', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'ACTIVE_MONITORED', 'SUMMER_AUTUMN'),
  ('poroshiri-dake', '幌尻岳', 'HOKKAIDO', 'HOKKAIDO', '日高山脈', array['北海道']::text[], 2052, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'EXTREME', 'STEEP_ROCKY', 'NOT_NEEDED', 'UNRELIABLE', 'BASIC_NO_BEDDING', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'REMOTE', 'POOR', 'HIGH', 'NONE', 'SUMMER_AUTUMN'),
  ('meakan-dake', '雌阿寒岳', 'HOKKAIDO', 'HOKKAIDO', '阿寒山群', array['北海道']::text[], 1499, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'RECOMMENDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'FULL_DAY', 'MODERATE', 'PARTIAL', 'MODERATE', 'ACTIVE_MONITORED', 'SNOW_FREE'),
  ('bandai-san', '磐梯山', 'TOHOKU', 'TOHOKU', '磐梯山', array['福島県']::text[], 1816, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'MODERATE', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'FULL_DAY', 'MODERATE', 'PARTIAL', 'MODERATE', 'ACTIVE_MONITORED', 'SNOW_FREE'),
  ('azuma-yama', '吾妻山', 'TOHOKU', 'TOHOKU', '吾妻連峰', array['山形県', '福島県']::text[], 2035, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'RECOMMENDED', 'LIMITED_OR_SEASONAL', 'BASIC_NO_BEDDING', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'ACTIVE_MONITORED', 'SNOW_FREE'),
  ('aizu-komagatake', '会津駒ヶ岳', 'TOHOKU', 'TOHOKU', '会津駒ヶ岳', array['福島県']::text[], 2133, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'BASIC_NO_BEDDING', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('hiuchi-gatake', '燧ヶ岳', 'TOHOKU', 'TOHOKU', '尾瀬', array['福島県']::text[], 2356, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'FULL_SERVICE', 'DESIGNATED', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('shibutsu-san', '至仏山', 'HOKUSHINETSU', 'HOKUSHINETSU', '尾瀬', array['群馬県']::text[], 2228, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'FULL_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('hotaka-yama', '武尊山', 'KANTO', 'KANTO', '上州武尊山', array['群馬県']::text[], 2158, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SNOW_FREE'),
  ('akagi-yama', '赤城山', 'KANTO', 'KANTO', '赤城山', array['群馬県']::text[], 1828, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'MODERATE', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'SUBALPINE_FOREST', 'LOW', 'FULL_DAY', 'MODERATE', 'PARTIAL', 'MODERATE', 'ACTIVE_MONITORED', 'SNOW_FREE'),
  ('sukai-san', '皇海山', 'KANTO', 'KANTO', '足尾山地', array['栃木県', '群馬県']::text[], 2144, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'CHAIN_LADDER', 'RECOMMENDED', 'UNRELIABLE', 'NONE', 'NONE', 'SUBALPINE_FOREST', 'SEASONAL_PATCHES', 'LONG_DAY', 'REMOTE', 'POOR', 'MODERATE', 'NONE', 'SNOW_FREE'),
  ('nasu-dake', '那須岳', 'KANTO', 'KANTO', '那須連山', array['栃木県', '福島県']::text[], 1915, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'RECOMMENDED', 'LIMITED_OR_SEASONAL', 'FULL_SERVICE', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'FULL_DAY', 'MODERATE', 'PARTIAL', 'MODERATE', 'ACTIVE_MONITORED', 'SNOW_FREE'),
  ('hiragatake', '平ヶ岳', 'HOKUSHINETSU', 'HOKUSHINETSU', '越後山脈', array['群馬県', '新潟県']::text[], 2141, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'EXTREME', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'UNRELIABLE', 'NONE', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'LONG_DAY', 'REMOTE', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('echigo-komagatake', '越後駒ヶ岳', 'HOKUSHINETSU', 'HOKUSHINETSU', '越後山脈', array['新潟県']::text[], 2003, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'BASIC_NO_BEDDING', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('makihata-yama', '巻機山', 'HOKUSHINETSU', 'HOKUSHINETSU', '越後山脈', array['新潟県', '群馬県']::text[], 1967, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('myoko-san', '妙高山', 'HOKUSHINETSU', 'HOKUSHINETSU', '頸城山塊', array['新潟県']::text[], 2454, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'BASIC_NO_BEDDING', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'ACTIVE_MONITORED', 'SUMMER_AUTUMN'),
  ('hiuchi-yama', '火打山', 'HOKUSHINETSU', 'HOKUSHINETSU', '頸城山塊', array['新潟県']::text[], 2462, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'FULL_SERVICE', 'DESIGNATED', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('azumaya-san', '四阿山', 'HOKUSHINETSU', 'HOKUSHINETSU', '菅平高原', array['長野県', '群馬県']::text[], 2354, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'MODERATE', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'FULL_DAY', 'MODERATE', 'PARTIAL', 'MODERATE', 'ACTIVE_MONITORED', 'SNOW_FREE'),
  ('tsukuba-san', '筑波山', 'KANTO', 'KANTO', '筑波山地', array['茨城県']::text[], 877, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'FRONT_COUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'LOW', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'TREATED_RELIABLE', 'NONE', 'NONE', 'LOWLAND_FOREST', 'LOW', 'HALF_DAY', 'EASY', 'RELIABLE', 'LOW', 'NONE', 'YEAR_ROUND'),
  ('ryokami-san', '両神山', 'OKUCHICHIBU', 'OKUCHICHIBU', '奥秩父山塊', array['埼玉県']::text[], 1723, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'CHAIN_LADDER', 'RECOMMENDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'SUBALPINE_FOREST', 'LOW', 'FULL_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SNOW_FREE'),
  ('kobushi-gatake', '甲武信ヶ岳', 'OKUCHICHIBU', 'OKUCHICHIBU', '奥秩父山塊', array['埼玉県', '山梨県', '長野県']::text[], 2475, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'OVERNIGHT_BACKPACKING', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'NATURAL_RELIABLE', 'FULL_SERVICE', 'DESIGNATED', 'SUBALPINE_FOREST', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SNOW_FREE'),
  ('amagi-san', '天城山', 'TOKAI', 'TOKAI', '天城山地', array['静岡県']::text[], 1406, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'MODERATE', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'LOWLAND_FOREST', 'LOW', 'FULL_DAY', 'MODERATE', 'PARTIAL', 'LOW', 'NONE', 'YEAR_ROUND'),
  ('houou-san', '鳳凰山', 'SOUTHERN_ALPS', 'SOUTHERN_ALPS', '南アルプス', array['山梨県']::text[], 2841, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('senjo-gatake', '仙丈ヶ岳', 'SOUTHERN_ALPS', 'SOUTHERN_ALPS', '南アルプス', array['山梨県', '長野県']::text[], 3033, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('aino-dake', '間ノ岳', 'SOUTHERN_ALPS', 'SOUTHERN_ALPS', '南アルプス', array['山梨県', '静岡県']::text[], 3190, true, array['SUMMER', 'AUTUMN']::text[], array['OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'LIMITED', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('shiomi-dake', '塩見岳', 'SOUTHERN_ALPS', 'SOUTHERN_ALPS', '南アルプス', array['長野県', '静岡県']::text[], 3052, true, array['SUMMER', 'AUTUMN']::text[], array['OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'LIMITED', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('warusawa-dake', '悪沢岳', 'SOUTHERN_ALPS', 'SOUTHERN_ALPS', '南アルプス', array['静岡県']::text[], 3141, true, array['SUMMER', 'AUTUMN']::text[], array['OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'EXTREME', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'REMOTE', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('akaishi-dake', '赤石岳', 'SOUTHERN_ALPS', 'SOUTHERN_ALPS', '南アルプス', array['長野県', '静岡県']::text[], 3121, true, array['SUMMER', 'AUTUMN']::text[], array['OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'EXTREME', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'REMOTE', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('hijiri-dake', '聖岳', 'SOUTHERN_ALPS', 'SOUTHERN_ALPS', '南アルプス', array['長野県', '静岡県']::text[], 3013, true, array['SUMMER', 'AUTUMN']::text[], array['OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'EXTREME', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'REMOTE', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('tekari-dake', '光岳', 'SOUTHERN_ALPS', 'SOUTHERN_ALPS', '南アルプス', array['長野県', '静岡県']::text[], 2592, true, array['SUMMER', 'AUTUMN']::text[], array['OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'BASIC_NO_BEDDING', 'DESIGNATED', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'MULTI_DAY', 'REMOTE', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('norikura-dake', '乗鞍岳', 'NORTHERN_ALPS', 'NORTHERN_ALPS', '北アルプス', array['長野県', '岐阜県']::text[], 3026, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'MODERATE', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'FULL_DAY', 'MODERATE', 'PARTIAL', 'LOW', 'ACTIVE_MONITORED', 'SUMMER_AUTUMN'),
  ('ontake-san', '御嶽山', 'TOKAI', 'TOKAI', '御嶽山', array['長野県', '岐阜県']::text[], 3067, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'TECHNICAL_SAFETY_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'RECOMMENDED', 'LIMITED_OR_SEASONAL', 'BASIC_NO_BEDDING', 'NONE', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'ACTIVE_RESTRICTED', 'SUMMER_AUTUMN'),
  ('goryu-dake', '五竜岳', 'NORTHERN_ALPS', 'NORTHERN_ALPS', '北アルプス', array['長野県', '富山県']::text[], 2814, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'TECHNICAL_SAFETY_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'EXTREME', 'EXPOSED_SCRAMBLE', 'RECOMMENDED', 'HUT_OR_SHOP_RELIABLE', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'LIMITED', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('kashimayari-gatake', '鹿島槍ヶ岳', 'NORTHERN_ALPS', 'NORTHERN_ALPS', '北アルプス', array['長野県', '富山県']::text[], 2889, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'TECHNICAL_SAFETY_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'EXTREME', 'EXPOSED_SCRAMBLE', 'RECOMMENDED', 'HUT_OR_SHOP_RELIABLE', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'LIMITED', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('kasagatake', '笠ヶ岳', 'NORTHERN_ALPS', 'NORTHERN_ALPS', '北アルプス', array['岐阜県']::text[], 2898, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'HUT_OR_SHOP_RELIABLE', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'LIMITED', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('kurobe-goro-dake', '黒部五郎岳', 'NORTHERN_ALPS', 'NORTHERN_ALPS', '北アルプス', array['富山県', '岐阜県']::text[], 2840, true, array['SUMMER', 'AUTUMN']::text[], array['OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'HUT_OR_SHOP_RELIABLE', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'REMOTE', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('yakushi-dake', '薬師岳', 'NORTHERN_ALPS', 'NORTHERN_ALPS', '北アルプス', array['富山県']::text[], 2926, true, array['SUMMER', 'AUTUMN']::text[], array['OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'HUT_OR_SHOP_RELIABLE', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'REMOTE', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('suisho-dake', '水晶岳', 'NORTHERN_ALPS', 'NORTHERN_ALPS', '北アルプス', array['富山県']::text[], 2986, true, array['SUMMER', 'AUTUMN']::text[], array['OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'EXTREME', 'STEEP_ROCKY', 'NOT_NEEDED', 'HUT_OR_SHOP_RELIABLE', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'REMOTE', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('washiba-dake', '鷲羽岳', 'NORTHERN_ALPS', 'NORTHERN_ALPS', '北アルプス', array['富山県', '長野県']::text[], 2924, true, array['SUMMER', 'AUTUMN']::text[], array['OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'EXTREME', 'STEEP_ROCKY', 'NOT_NEEDED', 'HUT_OR_SHOP_RELIABLE', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'REMOTE', 'POOR', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('kirigamine', '霧ヶ峰', 'HOKUSHINETSU', 'HOKUSHINETSU', '霧ヶ峰', array['長野県']::text[], 1925, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'FRONT_COUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'LOW', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'TREATED_RELIABLE', 'NONE', 'NONE', 'ABOVE_TREELINE', 'LOW', 'HALF_DAY', 'EASY', 'RELIABLE', 'LOW', 'NONE', 'YEAR_ROUND'),
  ('utsukushigahara', '美ヶ原', 'HOKUSHINETSU', 'HOKUSHINETSU', '美ヶ原', array['長野県']::text[], 2034, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'FRONT_COUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'LOW', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'TREATED_RELIABLE', 'NONE', 'NONE', 'ABOVE_TREELINE', 'LOW', 'HALF_DAY', 'EASY', 'RELIABLE', 'LOW', 'NONE', 'YEAR_ROUND'),
  ('arashima-dake', '荒島岳', 'HOKURIKU', 'HOKURIKU', '越美山地', array['福井県']::text[], 1523, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'MODERATE', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'SUBALPINE_FOREST', 'LOW', 'FULL_DAY', 'MODERATE', 'PARTIAL', 'MODERATE', 'NONE', 'SNOW_FREE'),
  ('hakusan', '白山', 'HOKURIKU', 'HOKURIKU', '白山山系', array['石川県', '岐阜県']::text[], 2702, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT', 'OVERNIGHT_TENT', 'MULTI_DAY_TREK']::text[], 'ALPINE_TREK', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'HUT_OR_SHOP_RELIABLE', 'FULL_SERVICE', 'DESIGNATED', 'HIGH_ALPINE_EXPOSED', 'SEASONAL_PATCHES', 'MULTI_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'ACTIVE_MONITORED', 'SUMMER_AUTUMN'),
  ('ibuki-yama', '伊吹山', 'KINKI', 'KINKI', '伊吹山地', array['滋賀県']::text[], 1377, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'FRONT_COUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'LOW', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'TREATED_RELIABLE', 'NONE', 'NONE', 'LOWLAND_FOREST', 'LOW', 'HALF_DAY', 'EASY', 'RELIABLE', 'LOW', 'NONE', 'YEAR_ROUND'),
  ('omine-san', '大峰山（八経ヶ岳）', 'KINKI', 'KINKI', '大峰山脈', array['奈良県']::text[], 1915, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE', 'OVERNIGHT_HUT']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'SHELTER_SYSTEM', 'SLEEP_SYSTEM', 'COOK_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'BASIC_NO_BEDDING', 'NONE', 'SUBALPINE_FOREST', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SNOW_FREE'),
  ('o-dai-ga-hara', '大台ヶ原山', 'KINKI', 'KINKI', '台高山脈', array['奈良県', '三重県']::text[], 1695, true, array['SPRING', 'SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'MODERATE', 'MAINTAINED_TRAIL', 'NOT_NEEDED', 'TREATED_RELIABLE', 'NONE', 'NONE', 'SUBALPINE_FOREST', 'LOW', 'FULL_DAY', 'MODERATE', 'PARTIAL', 'MODERATE', 'NONE', 'SNOW_FREE'),
  ('amakazari-yama', '雨飾山', 'HOKUSHINETSU', 'HOKUSHINETSU', '頸城山塊', array['新潟県', '長野県']::text[], 1963, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'STEEP_ROCKY', 'NOT_NEEDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('takatsuma-yama', '高妻山', 'HOKUSHINETSU', 'HOKUSHINETSU', '戸隠連峰', array['長野県', '新潟県']::text[], 2353, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'EXTREME', 'STEEP_ROCKY', 'NOT_NEEDED', 'UNRELIABLE', 'NONE', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'LONG_DAY', 'LIMITED', 'PARTIAL', 'MODERATE', 'NONE', 'SUMMER_AUTUMN'),
  ('kusatsu-shirane-san', '草津白根山', 'HOKUSHINETSU', 'HOKUSHINETSU', '草津白根山', array['群馬県']::text[], 2171, true, array['SUMMER', 'AUTUMN']::text[], array['DAY_HIKE']::text[], 'BACKCOUNTRY_DAY_HIKE', array['WATER_SYSTEM', 'RAIN_SYSTEM', 'COLD_WEATHER_LAYER', 'NAVIGATION_SYSTEM', 'EMERGENCY_SYSTEM']::text[], 'HIGH', 'MAINTAINED_TRAIL', 'RECOMMENDED', 'LIMITED_OR_SEASONAL', 'NONE', 'NONE', 'ABOVE_TREELINE', 'SEASONAL_PATCHES', 'FULL_DAY', 'MODERATE', 'PARTIAL', 'MODERATE', 'ACTIVE_RESTRICTED', 'SUMMER_AUTUMN')
on conflict (slug) do update
set
    name_ja = excluded.name_ja,
    region = excluded.region,
    primary_region = excluded.primary_region,
    mountain_range = excluded.mountain_range,
    prefectures = excluded.prefectures,
    elevation_m = excluded.elevation_m,
    is_hyakumeizan = excluded.is_hyakumeizan,
    supported_seasons = excluded.supported_seasons,
    supported_styles = excluded.supported_styles,
    trip_profile = excluded.trip_profile,
    typical_required_systems = excluded.typical_required_systems,
    route_seriousness = excluded.route_seriousness,
    technical_terrain = excluded.technical_terrain,
    helmet_guidance = excluded.helmet_guidance,
    water_availability = excluded.water_availability,
    hut_support = excluded.hut_support,
    tent_site_availability = excluded.tent_site_availability,
    alpine_environment = excluded.alpine_environment,
    snow_or_ice_risk = excluded.snow_or_ice_risk,
    route_duration_band = excluded.route_duration_band,
    escape_options = excluded.escape_options,
    cell_signal_reliability = excluded.cell_signal_reliability,
    bear_or_wildlife_risk = excluded.bear_or_wildlife_risk,
    volcanic_risk = excluded.volcanic_risk,
    season_opening_window = excluded.season_opening_window;
