alter table public.mountain_foundation_profiles
  add column if not exists active_volcano_status text not null default 'NONE'
    constraint mountain_foundation_profiles_active_volcano_status_check
    check (active_volcano_status in ('NONE', 'ACTIVE', 'ADJACENT')),
  add column if not exists jma_volcano_name text,
  add column if not exists jma_alert_url text,
  add column if not exists jma_constant_monitoring boolean,
  add column if not exists restriction_status_note text,
  add column if not exists snow_free_month_guide smallint
    constraint mountain_foundation_profiles_snow_free_month_guide_check
    check (snow_free_month_guide is null or snow_free_month_guide between 1 and 12),
  add column if not exists mandatory_gear_note text,
  add column if not exists supplementary_notes text;

update public.mountain_foundation_profiles as profile
set active_volcano_status = source.active_volcano_status,
    jma_volcano_name = source.jma_volcano_name,
    jma_alert_url = source.jma_alert_url,
    jma_constant_monitoring = source.jma_constant_monitoring,
    restriction_status_note = source.restriction_status_note,
    snow_free_month_guide = source.snow_free_month_guide,
    mandatory_gear_note = source.mandatory_gear_note,
    supplementary_notes = source.supplementary_notes
from (
  values
  ('tomuraushi-yama', 'NONE', null, null, null, null, 7, '防寒・気象急変対策（長丁場）', '2009年遭難の地。短縮路でも長時間'),
  ('aso-san', 'ACTIVE', '阿蘇山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/503.html', true, '火山(変動)', 4, '火山ガス対策（呼吸器・心疾患者は自粛）', '中岳はレベル連動で規制。2026年もヘリ事故で火口見学規制中。杵島岳等は常時可'),
  ('warusawa-dake', 'NONE', null, null, null, null, 7, null, '南アルプス深部。荒川三山縦走'),
  ('adatara-yama', 'ACTIVE', '安達太良山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/214.html', true, '火山(変動)', 6, null, '沼ノ平火口付近に火山ガス。レベル連動'),
  ('ibuki-yama', 'NONE', null, null, null, null, 4, null, '冬季は積雪多いが標高低め'),
  ('amakazari-yama', 'NONE', null, null, null, null, 7, null, '残雪が遅い。紅葉期人気'),
  ('kumotori-yama', 'NONE', null, null, null, null, 5, null, '厳冬期は積雪。通年入山可'),
  ('echigo-komagatake', 'NONE', null, null, null, null, 7, null, '豪雪地帯で残雪多い'),
  ('tsubakuro-dake', 'NONE', null, null, null, null, 7, null, '表銀座の起点'),
  ('shiomi-dake', 'NONE', null, null, null, null, 7, null, '南アルプス深部'),
  ('okuhotakadake', 'NONE', null, null, null, null, 7, 'ヘルメット推奨（岩稜・落石）', '日帰り不可。標準は小屋泊/テント泊'),
  ('hiuchi-yama', 'ADJACENT', null, null, null, null, 7, '6月中旬まで残雪・軽アイゼン推奨', '6月中旬まで残雪。高谷池ヒュッテにテント場あり、妙高と縦走可。※火山名は隣接の新潟焼山(307)で火打山本体は非活火山'),
  ('aizu-komagatake', 'NONE', null, null, null, null, 7, null, '豪雪。木道・湿原'),
  ('kaimon-dake', 'ACTIVE', '開聞岳', 'https://www.data.jma.go.jp/vois/data/report/activity_info/507.html', false, '活火山(静穏)', 1, null, '活火山だが静穏（常時観測外）。通年登山可'),
  ('kasagatake', 'NONE', null, null, null, null, 7, null, '笠新道は長大・健脚向け。標準は小屋泊'),
  ('kentoku-san', 'NONE', null, null, null, null, 5, '山頂直下「鳳岩」に鎖場', null),
  ('makihata-yama', 'NONE', null, null, null, null, 7, null, '豪雪地帯'),
  ('aino-dake', 'NONE', null, null, null, null, 7, null, '白峰三山縦走。日帰り不可'),
  ('iwate-san', 'ACTIVE', '岩手山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/207.html', true, '火山(変動)', 7, null, '2026/06時点 噴火警戒レベル2（火口周辺規制）'),
  ('iwaki-san', 'ACTIVE', '岩木山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/202.html', true, '火山(変動)', 6, null, 'レベル連動。ふだんは静穏。スカイライン/リフトあり'),
  ('miyanoura-dake', 'NONE', null, null, null, null, 4, '雨具必須（多雨）', '荒川登山口は時期によりマイカー規制（バス）。屋久島・非火山'),
  ('kinpu-san', 'NONE', null, null, null, null, 6, null, '大弛峠林道は冬季閉鎖'),
  ('kuju-san', 'ACTIVE', '九重山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/502.html', true, '火山(変動)', 4, '硫黄山周辺は火山ガス注意', 'レベル連動。坊ガツルでテント泊・くじゅう連山縦走'),
  ('utsugi-dake', 'NONE', null, null, null, null, 7, null, '木曽駒〜檜尾〜空木の縦走路の一部。檜尾小屋(テント場)あり'),
  ('gassan', 'NONE', null, null, null, null, 7, null, '豪雪。春は山スキー。登拝は7月〜'),
  ('tsurugi-san-shikoku', 'NONE', null, null, null, null, 5, null, 'リフトあり。四国・非火山'),
  ('goryu-dake', 'NONE', null, null, null, null, 7, null, '八峰キレット縦走時はヘルメット推奨'),
  ('azuma-yama', 'ACTIVE', '吾妻山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/213.html', true, '火山(変動)', 6, null, '一切経山・大穴火口で火山ガス。レベル連動'),
  ('ontake-san', 'ACTIVE', '御嶽山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/312.html', true, '火山(変動)', 7, 'ヘルメット必携（登山口から着用推奨）・火山ガス注意', '剣ヶ峰は夏季限定開放（例年7/1〜10月中旬）。火口500m規制。八合目〜三ノ池はアイゼン/ピッケル必須'),
  ('tekari-dake', 'NONE', null, null, null, null, 7, null, '南アルプス最深部。光小屋'),
  ('kaikoma-gatake', 'NONE', null, null, null, null, 7, '黒戸尾根は鎖場・梯子の長大ルート', '北沢峠からは比較的容易'),
  ('kobushi-gatake', 'NONE', null, null, null, null, 6, null, '奥秩父主脈縦走'),
  ('sukai-san', 'NONE', null, null, null, '通行規制', 6, '（現状）長大ルート・読図・熊対策', '栗原川林道が恒久閉鎖。短絡路(不動沢)廃道。庚申山経由の長大ルートのみ。日帰り前提は危険'),
  ('arashima-dake', 'NONE', null, null, null, null, 5, null, '豪雪地帯（福井）'),
  ('takatsuma-yama', 'NONE', null, null, null, null, 7, null, '戸隠側。急登・長時間'),
  ('takao-san', 'NONE', null, null, null, null, 1, null, '通年。ケーブルカーあり'),
  ('kurobe-goro-dake', 'NONE', null, null, null, null, 7, null, '北アルプス深部。縦走'),
  ('azumaya-san', 'NONE', null, null, null, null, 6, null, '非活火山（古い火山）'),
  ('shibutsu-san', 'NONE', null, null, null, null, 7, null, '残雪期植生保護で例年7/1まで時期規制。鳩待峠ルートに一方通行規制あり'),
  ('meakan-dake', 'ACTIVE', '雌阿寒岳', 'https://www.data.jma.go.jp/vois/data/report/activity_info/105.html', true, '火山(変動)', 6, null, '2026/06時点 噴火警戒レベル2（火口周辺規制）。北海道のため春は積雪期＝季節データ要見直し'),
  ('kashimayari-gatake', 'NONE', null, null, null, null, 7, '八峰キレット縦走時はヘルメット推奨', null),
  ('tokachi-dake', 'ACTIVE', '十勝岳', 'https://www.data.jma.go.jp/vois/data/report/activity_info/108.html', true, '火山(変動)', 7, null, '活発期あり。2026/06はレベル1。レベル連動'),
  ('yakedake', 'ACTIVE', '焼岳', 'https://www.data.jma.go.jp/vois/data/report/activity_info/310.html', true, '火山(変動)', 6, 'ヘルメット推奨・火山ガス/噴気帯注意', '気象庁も登山時のヘルメット着用を呼びかけ。レベル連動'),
  ('norikura-dake', 'ACTIVE', '乗鞍岳', 'https://www.data.jma.go.jp/vois/data/report/activity_info/311.html', true, '火山(変動)', 7, null, '畳平までバス。小屋泊も可。活火山だが近年静穏'),
  ('jonen-dake', 'NONE', null, null, null, null, 7, null, '常念山脈縦走。日帰り不可'),
  ('suisho-dake', 'NONE', null, null, null, null, 7, null, '北アルプス最深部'),
  ('mizugaki-yama', 'NONE', null, null, null, null, 5, null, '岩稜だが一般道は鎖場補助あり'),
  ('hijiri-dake', 'NONE', null, null, null, null, 7, null, '南アルプス深部'),
  ('nishihotaka-dake', 'NONE', null, null, null, null, 7, 'ヘルメット推奨（独標以遠の岩稜）', 'ロープウェイで独標まで容易。西穂〜奥穂は上級'),
  ('ishizuchi-san', 'NONE', null, null, null, null, 5, '鎖場（自信なければ迂回路）', '西日本最高峰。冬季は本格雪山'),
  ('aka-dake', 'NONE', null, null, null, null, 6, null, '八ヶ岳主峰。非活火山'),
  ('akagi-yama', 'ACTIVE', '赤城山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/303.html', false, '活火山(静穏)', 5, null, '活火山だが静穏（常時観測外）。有史の噴火記録は議論あり'),
  ('akaishi-dake', 'NONE', null, null, null, null, 7, null, '南アルプス。縦走'),
  ('senjo-gatake', 'NONE', null, null, null, null, 7, null, '北沢峠から。比較的登りやすい'),
  ('asama-yama', 'ACTIVE', '浅間山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/306.html', true, '火山(変動)', 6, null, 'レベルで到達範囲が変動（L1=前掛山/L2=外輪山のみ）。2026/05/22にL1化で前掛山が約3年ぶり再開。真の最高点(釜山)は常時不可'),
  ('sobo-san', 'NONE', null, null, null, null, 4, null, '非火山'),
  ('yarigatake', 'NONE', null, null, null, null, 7, 'ヘルメット推奨（穂先・落石）', '日帰り不可。標準は小屋泊/テント泊'),
  ('kusatsu-shirane-san', 'ACTIVE', '草津白根山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/305.html', true, '火山(変動)', 6, '（現状）登山道閉鎖・火山ガス', '道路は2026/05再開もレベル1継続中、本白根山遊歩道等は立入禁止・未整備で登山不可。規制は白根山(湯釜付近350)・本白根山で発表'),
  ('zao-san', 'ACTIVE', '蔵王山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/212.html', true, '火山(変動)', 6, null, '御釜付近でレベル連動。エコーライン開通は4月下旬'),
  ('daisen', 'NONE', null, null, null, '一部立入規制', 5, null, '最高点・剣ヶ峰は崩落で立入不可。一般は弥山まで。非活火山'),
  ('daisetsuzan-asahi-dake', 'ACTIVE', '大雪山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/107.html', true, '火山(変動)', 7, null, '地獄谷の火山ガス。レベル連動。ロープウェイあり'),
  ('o-dai-ga-hara', 'NONE', null, null, null, null, 5, null, 'ドライブウェイは冬季閉鎖（12〜4月）'),
  ('daibosatsu-rei', 'NONE', null, null, null, null, 5, null, '上日川峠から容易。テント泊/縦走はやや慷慨な分類'),
  ('omine-san', 'NONE', null, null, null, null, 5, null, '近畿最高峰。八経ヶ岳本体は一般道'),
  ('tanigawa-dake', 'NONE', null, null, null, null, 6, '気象急変・撤退判断（西黒尾根は岩場）', '遭難者数最多級。ロープウェイあり。冬季は超上級'),
  ('tanzawa-san', 'NONE', null, null, null, null, 4, null, '冬季も入山可（軽アイゼンが要る日も）'),
  ('tsukuba-san', 'NONE', null, null, null, null, 1, null, '通年。ケーブルカー/ロープウェイ'),
  ('cho-gatake', 'NONE', null, null, null, null, 7, null, '常念山脈。展望地'),
  ('chokai-san', 'ACTIVE', '鳥海山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/209.html', true, '火山(変動)', 7, null, '活火山・静穏寄りだがレベル連動。豪雪で残雪多い'),
  ('amagi-san', 'NONE', null, null, null, null, 3, null, '伊豆。温暖。非活火山（監視は別位置の伊豆東部火山群）'),
  ('karamatsu-dake', 'NONE', null, null, null, null, 7, null, '八方尾根。比較的登りやすい'),
  ('tono-dake', 'NONE', null, null, null, null, 4, null, '通年人気。尊仏山荘は通年営業'),
  ('nasu-dake', 'ACTIVE', '那須岳', 'https://www.data.jma.go.jp/vois/data/report/activity_info/301.html', true, '火山(変動)', 6, '強風帯（防風対策）', '茶臼岳火口でレベル連動。ロープウェイあり'),
  ('nikko-shirane-san', 'ACTIVE', '日光白根山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/302.html', true, '火山(変動)', 6, null, '活火山。ふだん静穏。ロープウェイあり'),
  ('hakusan', 'ACTIVE', '白山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/313.html', true, '火山(変動)', 7, null, '活火山・静穏。南竜ヶ馬場でテント泊・別山縦走'),
  ('shirouma-dake', 'NONE', null, null, null, null, 7, '大雪渓で夏も軽アイゼン/チェーンスパイク推奨', '非火山だが大雪渓が核心'),
  ('hakkoda-san', 'ACTIVE', '八甲田山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/203.html', true, '火山(変動)', 6, '火山ガス注意（過去にガス事故）', '大岳周辺。レベル連動。ロープウェイあり'),
  ('bandai-san', 'ACTIVE', '磐梯山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/215.html', true, '火山(変動)', 5, null, 'レベル連動。ふだん静穏'),
  ('utsukushigahara', 'NONE', null, null, null, null, 5, null, '車でアクセス可。非活火山'),
  ('naeba-san', 'NONE', null, null, null, null, 7, null, '豪雪。山頂湿原'),
  ('fuji-san', 'ACTIVE', '富士山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/314.html', true, '火山(変動)', 7, '防寒・高山病対策（弾丸登山非推奨）', '開山は盛夏のみ。テント泊不可（路線上禁止）。活火山だが現在静穏'),
  ('hotaka-yama', 'NONE', null, null, null, null, 6, null, '非活火山（古い火山）'),
  ('hiragatake', 'NONE', null, null, null, null, 7, '防寒・長時間対策', '日本屈指の長大日帰り（約12時間）'),
  ('houou-san', 'NONE', null, null, null, null, 7, null, '地蔵・観音・薬師。縦走'),
  ('kita-dake', 'NONE', null, null, null, null, 7, null, '日本第2の高峰。広河原から'),
  ('poroshiri-dake', 'NONE', null, null, null, null, 7, '額平川の渡渉装備（替え靴/沢靴・増水時は中止）', '渡渉が核心。北海道・非火山。ヒグマ対策も'),
  ('myoko-san', 'ACTIVE', '妙高山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/308.html', true, '火山(変動)', 7, null, '活火山だが静穏。黒沢池/高谷池でテント泊・火打と縦走可'),
  ('kirigamine', 'NONE', null, null, null, null, 5, null, '車でアクセス可。非活火山'),
  ('kirishima-yama', 'ACTIVE', '霧島山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/505.html', true, '火山(変動)', 4, null, '2026/06時点 新燃岳レベル2・硫黄山も活動。韓国岳/高千穂峰は個別登山に。縦走路一部不可。個別ページ:新燃岳551・えびの硫黄山・御鉢'),
  ('kiso-komagatake', 'NONE', null, null, null, null, 7, null, 'ロープウェイで千畳敷へ。空木へ縦走可'),
  ('yakushi-dake', 'NONE', null, null, null, null, 7, null, '北アルプス。雲ノ平方面'),
  ('yotei-zan', 'ACTIVE', '羊蹄山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/117.html', false, '活火山(静穏)', 7, null, '活火山だが有史の噴火記録なし・常時観測外。北海道'),
  ('rausu-dake', 'ACTIVE', '羅臼岳', 'https://www.data.jma.go.jp/vois/data/report/activity_info/102.html', false, '活火山(静穏)', 7, 'ヒグマ対策必須（フードコンテナ等）', '活火山・静穏（常時観測外）。知床'),
  ('rishiri-zan', 'ACTIVE', '利尻山', 'https://www.data.jma.go.jp/vois/data/report/activity_info/116.html', false, '活火山(静穏)', 7, '携帯トイレ必携（山中トイレ無）', '活火山・静穏（常時観測外）。離島・長時間'),
  ('tateyama', 'ACTIVE', '弥陀ヶ原', 'https://www.data.jma.go.jp/vois/data/report/activity_info/309.html', true, '火山(変動)', 7, null, '監視名は「弥陀ヶ原」。地獄谷の火山ガス。室堂までアルペンルート。雷鳥沢でテント泊'),
  ('ryokami-san', 'NONE', null, null, null, null, 5, '鎖場（八丁尾根は上級／一般は表参道）', '奥秩父。清滝小屋は避難小屋'),
  ('washiba-dake', 'NONE', null, null, null, null, 7, null, '北アルプス最深部'),
  ('tsurugi-dake', 'NONE', null, null, null, null, 7, 'ヘルメット推奨（鎖場・カニのタテバイ/ヨコバイ）', '標準は剣沢/剣山荘ベースの小屋泊・テント泊。日帰りは超健脚の例外'),
  ('hiuchi-gatake', 'ACTIVE', '燧ヶ岳', 'https://www.data.jma.go.jp/vois/data/report/activity_info/216.html', false, '活火山(静穏)', 7, null, '活火山・静穏（常時観測外）。尾瀬'),
  ('tateshina-yama', 'NONE', null, null, null, null, 6, null, '北八ヶ岳北端。標準は日帰り。隣接の活火山は横岳(北横岳)で蓼科山本体は非監視')
) as source(
  slug,
  active_volcano_status,
  jma_volcano_name,
  jma_alert_url,
  jma_constant_monitoring,
  restriction_status_note,
  snow_free_month_guide,
  mandatory_gear_note,
  supplementary_notes
)
where profile.slug = source.slug;
