insert into public.gear_products (
  brand,
  model,
  name_ja,
  category_id,
  subcategory_id,
  weight_grams,
  official_weight_grams,
  measured_weight_grams,
  msrp_jpy,
  size,
  volume,
  color,
  material,
  capacity,
  official_url,
  image_url,
  released_at,
  discontinued,
  msrp_source_url,
  last_verified_at,
  verification_status
)
select
  v.brand,
  v.model,
  v.name_ja,
  c.id,
  s.id,
  v.official_weight_grams,
  v.official_weight_grams,
  null,
  v.msrp_jpy,
  v.size,
  null,
  v.color,
  null,
  null,
  v.official_url,
  v.image_url,
  null,
  false,
  v.msrp_source_url,
  date '2026-06-15',
  'verified'
from (
  values
    ('NANGA', 'オーロラテックス ライト350DX', 'オーロラテックス ライト350DX', 'sleep', 'sleeping_bag', 730, 47300, 'レギュラー', 'GRY', 'https://store.nanga.jp/products/aurora-tex-light-350-dx-1', 'https://cdn.shopify.com/s/files/1/0033/7428/4867/files/ONLINE_AURORA_light_GRY_OREG_01_9a910f78-0eca-40a7-a107-53b8c21e9e1c.jpg?v=1750211752', 'https://store.nanga.jp/products/aurora-tex-light-350-dx-1'),
    ('NANGA', 'オーロラテックス ライト450DX', 'オーロラテックス ライト450DX', 'sleep', 'sleeping_bag', 750, 52800, 'レギュラー', 'BRN', 'https://store.nanga.jp/products/aurora-tex-light-450dx-1', 'https://cdn.shopify.com/s/files/1/0033/7428/4867/files/ONLINE_AURORA_light_450DX_BRW.jpg?v=1776075595', 'https://store.nanga.jp/products/aurora-tex-light-450dx-1'),
    ('NANGA', 'オーロラテックス ライト600DX', 'オーロラテックス ライト600DX', 'sleep', 'sleeping_bag', 1100, 64900, 'レギュラー', 'BRW', 'https://store.nanga.jp/products/aurora-tex-light-600-dx-1', 'https://cdn.shopify.com/s/files/1/0033/7428/4867/files/ONLINE_AURORA_light_600DX_BRW_01_87a48920-1f29-4065-abbb-e9866b6f8542.jpg?v=1750211860', 'https://store.nanga.jp/products/aurora-tex-light-600-dx-1'),
    ('NANGA', 'オーロラテックス ライト750DX', 'オーロラテックス ライト750DX', 'sleep', 'sleeping_bag', 1280, 71500, 'レギュラー', 'GRY', 'https://store.nanga.jp/products/aurora-tex-light-750-dx-1', 'https://cdn.shopify.com/s/files/1/0033/7428/4867/files/ONLINE_AURORA_light_750DX_GRY_OREG_01_bf8f36de-8e71-49c1-92b7-b2afdfcf63e2.jpg?v=1750211857', 'https://store.nanga.jp/products/aurora-tex-light-750-dx-1'),
    ('NANGA', 'オーロラテックス ライト900DX', 'オーロラテックス ライト900DX', 'sleep', 'sleeping_bag', 1400, 77000, 'レギュラー', 'BLK', 'https://store.nanga.jp/products/aurora-tex-light-900-dx-1', 'https://cdn.shopify.com/s/files/1/0033/7428/4867/files/ONLINE_AURORA_light_900DX_BLK_NVY_03_0aed8161-f2fb-4442-a309-8d2a9de197dc.jpg?v=1750211855', 'https://store.nanga.jp/products/aurora-tex-light-900-dx-1'),
    ('NANGA', 'UDD バッグ 380DX', 'UDD バッグ 380DX', 'sleep', 'sleeping_bag', 680, 51700, 'レギュラー', 'RED', 'https://store.nanga.jp/products/udd-bag-380dx', 'https://cdn.shopify.com/s/files/1/0033/7428/4867/products/UDD_BAG_380DX_RED_02.jpg?v=1750211907', 'https://store.nanga.jp/products/udd-bag-380dx'),
    ('NANGA', 'UDD バッグ 450DX', 'UDD バッグ 450DX', 'sleep', 'sleeping_bag', 825, 58300, 'レギュラー', 'CHA', 'https://store.nanga.jp/products/udd-bag-450dx', 'https://cdn.shopify.com/s/files/1/0033/7428/4867/files/UDD_CHA.jpg?v=1750211905', 'https://store.nanga.jp/products/udd-bag-450dx'),
    ('NANGA', 'UDD バッグ 630DX', 'UDD バッグ 630DX', 'sleep', 'sleeping_bag', 1045, 69300, 'レギュラー', 'RED', 'https://store.nanga.jp/products/udd-bag-630dx-1', 'https://cdn.shopify.com/s/files/1/0033/7428/4867/files/UDD_BAG_04_a3216c4e-20a3-4f59-8d75-365b670793d2.jpg?v=1750211868', 'https://store.nanga.jp/products/udd-bag-630dx-1'),
    ('NANGA', 'UDD バッグ 810DX', 'UDD バッグ 810DX', 'sleep', 'sleeping_bag', 1260, 79200, 'レギュラー', 'BEG', 'https://store.nanga.jp/products/udd-bag-810dx-1', 'https://cdn.shopify.com/s/files/1/0033/7428/4867/files/UDD_BEG_253b45aa-5c8f-42e6-8fa9-7617714bfeae.jpg?v=1750211866', 'https://store.nanga.jp/products/udd-bag-810dx-1'),
    ('NANGA', 'ミニマリスム ゼロ', 'ミニマリスム ゼロ', 'sleep', 'sleeping_bag', 325, 49500, 'レギュラー', 'L.GRY', 'https://store.nanga.jp/products/minimarhythm-zero', 'https://cdn.shopify.com/s/files/1/0033/7428/4867/files/MINIMARHYTHMZERO_GRY_08facee7-35d0-48d0-9298-160ed673d678.jpg?v=1754354130', 'https://store.nanga.jp/products/minimarhythm-zero'),
    ('NANGA', 'ミニマリスム 5ビロー', 'ミニマリスム 5ビロー', 'sleep', 'sleeping_bag', 415, 57200, 'レギュラー', 'L.GRY', 'https://store.nanga.jp/products/minimarhythm-5below', 'https://cdn.shopify.com/s/files/1/0033/7428/4867/files/MINIMARHYTHM5BELOW_GRY.jpg?v=1775627139', 'https://store.nanga.jp/products/minimarhythm-5below'),
    ('NANGA', 'レベル8 -13 オーロラテックス ライト', 'レベル8 -13 オーロラテックス ライト', 'sleep', 'sleeping_bag', null, 90750, 'レギュラー', 'COYOTE', 'https://store.nanga.jp/products/level8-13-aurora-tex-light', 'https://cdn.shopify.com/s/files/1/0033/7428/4867/files/LEVEL8-13AURORATEXLight_COYOTE.jpg?v=1750211558', 'https://store.nanga.jp/products/level8-13-aurora-tex-light'),
    ('ISUKA', 'エアドライト 290', 'エアドライト 290', 'sleep', 'sleeping_bag', 560, 39600, null, null, 'https://www.isuka.co.jp/products/lineup/product.php?seq=239', 'https://www.isuka.co.jp/upload/product/main_image00000239.png', 'https://www.isuka.co.jp/products/lineup/product.php?seq=239'),
    ('ISUKA', 'エアドライト 480', 'エアドライト 480', 'sleep', 'sleeping_bag', 870, 50600, null, null, 'https://www.isuka.co.jp/products/lineup/product.php?seq=232', 'https://www.isuka.co.jp/upload/product/main_image00000232.png', 'https://www.isuka.co.jp/products/lineup/product.php?seq=232'),
    ('ISUKA', 'エアドライト 670', 'エアドライト 670', 'sleep', 'sleeping_bag', 1070, 63800, null, null, 'https://www.isuka.co.jp/products/lineup/product.php?seq=234', 'https://www.isuka.co.jp/upload/product/main_image00000234.png', 'https://www.isuka.co.jp/products/lineup/product.php?seq=234'),
    ('ISUKA', 'エアドライト 860', 'エアドライト 860', 'sleep', 'sleeping_bag', 1330, 75900, null, null, 'https://www.isuka.co.jp/products/lineup/product.php?seq=235', 'https://www.isuka.co.jp/upload/product/main_image00000235.png', 'https://www.isuka.co.jp/products/lineup/product.php?seq=235'),
    ('ISUKA', 'エアプラス 280', 'エアプラス 280', 'sleep', 'sleeping_bag', 550, 48400, null, null, 'https://www.isuka.co.jp/products/lineup/product.php?seq=241', 'https://www.isuka.co.jp/upload/product/main_image00000241.png', 'https://www.isuka.co.jp/products/lineup/product.php?seq=241'),
    ('ISUKA', 'エアプラス 450', 'エアプラス 450', 'sleep', 'sleeping_bag', 840, 66000, null, null, 'https://www.isuka.co.jp/products/lineup/product.php?seq=228', 'https://www.isuka.co.jp/upload/product/main_image00000228.png', 'https://www.isuka.co.jp/products/lineup/product.php?seq=228'),
    ('ISUKA', 'エアプラス 630', 'エアプラス 630', 'sleep', 'sleeping_bag', 1030, 85800, null, null, 'https://www.isuka.co.jp/products/lineup/product.php?seq=230', 'https://www.isuka.co.jp/upload/product/main_image00000230.png', 'https://www.isuka.co.jp/products/lineup/product.php?seq=230'),
    ('ISUKA', 'エアプラス 810', 'エアプラス 810', 'sleep', 'sleeping_bag', 1280, 105600, null, null, 'https://www.isuka.co.jp/products/lineup/product.php?seq=231', 'https://www.isuka.co.jp/upload/product/main_image00000231.png', 'https://www.isuka.co.jp/products/lineup/product.php?seq=231'),
    ('ISUKA', 'アルファライト NEO 300', 'アルファライト NEO 300', 'sleep', 'sleeping_bag', 670, 19800, null, null, 'https://www.isuka.co.jp/products/lineup/product.php?seq=257', 'https://www.isuka.co.jp/upload/product/main_image00000257.png', 'https://www.isuka.co.jp/products/lineup/product.php?seq=257'),
    ('ISUKA', 'アルファライト NEO 500', 'アルファライト NEO 500', 'sleep', 'sleeping_bag', 1090, 24200, null, null, 'https://www.isuka.co.jp/products/lineup/product.php?seq=258', 'https://www.isuka.co.jp/upload/product/main_image00000258.png', 'https://www.isuka.co.jp/products/lineup/product.php?seq=258'),
    ('ISUKA', 'ダウンプラス チロル X', 'ダウンプラス チロル X', 'sleep', 'sleeping_bag', 620, 25300, null, null, 'https://www.isuka.co.jp/products/lineup/product.php?seq=22', 'https://www.isuka.co.jp/upload/product/main_image00000022.png', 'https://www.isuka.co.jp/products/lineup/product.php?seq=22'),
    ('ISUKA', 'ダウンプラス ポカラ X', 'ダウンプラス ポカラ X', 'sleep', 'sleeping_bag', 1060, 38500, null, null, 'https://www.isuka.co.jp/products/lineup/product.php?seq=25', 'https://www.isuka.co.jp/upload/product/main_image00000025.png', 'https://www.isuka.co.jp/products/lineup/product.php?seq=25'),
    ('NEMO', 'Tensor Trail Regular Mummy', 'Tensor™ Trail レギュラー マミー', 'sleep', 'sleeping_pad', 369, 27500, 'レギュラー マミー', null, 'https://nemoequipment.jp/products/tensor-trail', 'https://cdn.shopify.com/s/files/1/0895/7431/0174/files/Tensor-Trail-RegularMummy_811666035073_01-Main_f2e34f7c-55de-4b7d-aa8b-f4fbb0d0aeb5.jpg?v=1734669343', 'https://nemoequipment.jp/products/tensor-trail'),
    ('NEMO', 'Tensor Elite Regular Mummy', 'Tensor™ Elite レギュラー マミー', 'sleep', 'sleeping_pad', 240, 35200, 'レギュラー マミー', null, 'https://nemoequipment.jp/products/tensor-elite', 'https://cdn.shopify.com/s/files/1/0895/7431/0174/files/f4e58f05e387e925674dccbcb8798307.jpg?v=1736146478', 'https://nemoequipment.jp/products/tensor-elite'),
    ('NEMO', 'Tensor All-Season Regular Mummy', 'Tensor™ All-Season レギュラー マミー', 'sleep', 'sleeping_pad', 400, 33000, 'レギュラー マミー', null, 'https://nemoequipment.jp/products/tensor-all-season', 'https://cdn.shopify.com/s/files/1/0895/7431/0174/files/Tensor-AllSeason-RegularMummy_811666035127_01-Main.jpg?v=1735122237', 'https://nemoequipment.jp/products/tensor-all-season'),
    ('NEMO', 'Tensor Extreme Conditions Regular Mummy', 'Tensor™ Extreme Conditions レギュラーマミー', 'sleep', 'sleeping_pad', 472, 38500, 'レギュラーマミー', null, 'https://nemoequipment.jp/products/tensor-extreme-conditions', 'https://cdn.shopify.com/s/files/1/0895/7431/0174/files/edit_Tensor-ExtremeConditions-RegularMummy_811666034281_01-Main.jpg?v=1736146375', 'https://nemoequipment.jp/products/tensor-extreme-conditions'),
    ('NEMO', 'Fillo', 'Fillo™', 'sleep', 'pillow', 260, 6930, null, 'ブルーホライゾン', 'https://nemoequipment.jp/products/fillo%E2%84%A2', 'https://cdn.shopify.com/s/files/1/0895/7431/0174/files/fillo_blue_horizon_main.jpg?v=1776923005', 'https://nemoequipment.jp/products/fillo%E2%84%A2'),
    ('NEMO', 'Fillo Elite', 'Fillo™ Elite', 'sleep', 'pillow', 80, 7480, null, 'ブラックパール', 'https://nemoequipment.jp/products/fillo%E2%84%A2-elite', 'https://cdn.shopify.com/s/files/1/0895/7431/0174/files/BlackPearlCitron1.jpg?v=1775526348', 'https://nemoequipment.jp/products/fillo%E2%84%A2-elite'),
    ('NEMO', 'Fillo Elite Wide', 'Fillo™ Elite Wide', 'sleep', 'pillow', 112, 8250, null, 'ブラック パール/シトロン', 'https://nemoequipment.jp/products/fillo-elite-wide', 'https://cdn.shopify.com/s/files/1/0895/7431/0174/files/fillo_elite_wide_black_pearl_main.jpg?v=1770130951', 'https://nemoequipment.jp/products/fillo-elite-wide'),
    ('NEMO', 'Dragonfly OSMO 1P', 'Dragonfly OSMO™ 1P', 'shelter', 'tent', 1000, 77000, '1P', 'Fog', 'https://nemoequipment.jp/products/dragonfly-osmo-1p', 'https://cdn.shopify.com/s/files/1/0895/7431/0174/files/dragonfly_osmo_1P_fog_main.jpg?v=1770126685', 'https://nemoequipment.jp/products/dragonfly-osmo-1p'),
    ('NEMO', 'Dragonfly OSMO 2P', 'Dragonfly OSMO™ 2P', 'shelter', 'tent', 1260, 85800, '2P', 'Fog', 'https://nemoequipment.jp/products/dragonfly-osmo-2p', 'https://cdn.shopify.com/s/files/1/0895/7431/0174/files/dragonfly_osmo_2P_fog_main.jpg?v=1770127953', 'https://nemoequipment.jp/products/dragonfly-osmo-2p'),
    ('NEMO', 'Dragonfly OSMO 3P', 'Dragonfly OSMO™ 3P', 'shelter', 'tent', 1540, 95700, '3P', 'Fog', 'https://nemoequipment.jp/products/dragonfly-osmo-3p', 'https://cdn.shopify.com/s/files/1/0895/7431/0174/files/dragonfly_osmo_3P_fog_sub1.jpg?v=1770128354', 'https://nemoequipment.jp/products/dragonfly-osmo-3p'),
    ('NEMO', 'Hornet OSMO 1P', 'Hornet™ OSMO™ 1P', 'shelter', 'tent', 822, 68200, '1P', 'Birch Bud', 'https://nemoequipment.jp/products/honet-osmo%E2%84%A2-%E3%83%9B%E3%83%BC%E3%83%8D%E3%83%83%E3%83%88-%E3%82%AA%E3%82%BA%E3%83%A2%E2%84%A2', 'https://cdn.shopify.com/s/files/1/0895/7431/0174/files/1P_0001__1.jpg?v=1736506349', 'https://nemoequipment.jp/products/honet-osmo%E2%84%A2-%E3%83%9B%E3%83%BC%E3%83%8D%E3%83%83%E3%83%88-%E3%82%AA%E3%82%BA%E3%83%A2%E2%84%A2'),
    ('NEMO', 'Tani OSMO 1P', 'Tani™ OSMO™ 1P', 'shelter', 'tent', 1120, 88000, '1P', 'Birch Bud', 'https://nemoequipment.jp/products/tani-osmo', 'https://cdn.shopify.com/s/files/1/0895/7431/0174/files/1P.jpg?v=1734668840', 'https://nemoequipment.jp/products/tani-osmo'),
    ('Therm-a-Rest', 'NeoAir XLite NXT Regular', 'NeoAir XLite NXT レギュラー', 'sleep', 'sleeping_pad', 369, null, 'Regular', 'Solar Flare', 'https://www.thermarest.com/sleeping-pads/fast-and-light/neoair-xlite-nxt-sleeping-pad/neoair-xlite-nxt.html', 'https://cdn.shopify.com/s/files/1/0574/0642/3174/files/11627_thermarest_neoair_xlite_nxt_solarflare_regular_angle.jpg?v=1724820257', 'https://www.thermarest.com/sleeping-pads/fast-and-light/neoair-xlite-nxt-sleeping-pad/neoair-xlite-nxt.html'),
    ('Therm-a-Rest', 'NeoAir XLite NXT MAX Regular Wide', 'NeoAir XLite NXT MAX レギュラーワイド', 'sleep', 'sleeping_pad', 539, null, 'Regular Wide', 'Solar Flare', 'https://www.thermarest.com/sleeping-pads/fast-and-light/neoair-xlite-nxt-max-sleeping-pad/neoair-xlite-nxt-max.html', 'https://cdn.shopify.com/s/files/1/0574/0642/3174/files/11631_thermarest_neoair_xlite_nxt_max_solarflare_regular_wide_angle.jpg?v=1724820254', 'https://www.thermarest.com/sleeping-pads/fast-and-light/neoair-xlite-nxt-max-sleeping-pad/neoair-xlite-nxt-max.html'),
    ('Therm-a-Rest', 'NeoAir XTherm NXT Regular', 'NeoAir XTherm NXT レギュラー', 'sleep', 'sleeping_pad', 439, null, 'Regular', 'Neptune', 'https://www.thermarest.com/sleeping-pads/fast-and-light/neoair-xtherm-nxt-sleeping-pad/neoair-xtherm-nxt.html', 'https://cdn.shopify.com/s/files/1/0574/0642/3174/files/11633_thermarest_neoair_xtherm_nxt_neptune_regular_angle_award.jpg?v=1724820257', 'https://www.thermarest.com/sleeping-pads/fast-and-light/neoair-xtherm-nxt-sleeping-pad/neoair-xtherm-nxt.html'),
    ('Therm-a-Rest', 'NeoAir XTherm NXT MAX Regular Wide', 'NeoAir XTherm NXT MAX レギュラーワイド', 'sleep', 'sleeping_pad', 652, null, 'Regular Wide', 'Neptune', 'https://www.thermarest.com/sleeping-pads/fast-and-light/neoair-r-xtherm-nxt-max-sleeping-pad/neoair-r-xtherm-nxt-max.html', 'https://cdn.shopify.com/s/files/1/0574/0642/3174/files/11636_thermarest_neoair_xtherm_nxt_max_neptune_regular_wide_angle.jpg?v=1724820256', 'https://www.thermarest.com/sleeping-pads/fast-and-light/neoair-r-xtherm-nxt-max-sleeping-pad/neoair-r-xtherm-nxt-max.html'),
    ('Therm-a-Rest', 'Z Lite SOL Regular', 'Z Lite SOL レギュラー', 'sleep', 'sleeping_pad', 397, null, 'Regular', 'Blue / Silver', 'https://www.thermarest.com/sleeping-pads/trek-and-travel/z-lite-sol-sleeping-pad/z-lite-sol.html', 'https://cdn.shopify.com/s/files/1/0574/0642/3174/files/06670_tr_zlite_sol_limonsilver_regular_silver_angle_fold.jpg?v=1728427656', 'https://www.thermarest.com/sleeping-pads/trek-and-travel/z-lite-sol-sleeping-pad/z-lite-sol.html'),
    ('Therm-a-Rest', 'Original Z Lite', 'Original Z Lite', 'sleep', 'sleeping_pad', 397, null, null, 'Coyote / Gray', 'https://www.thermarest.com/sleeping-pads/trek-and-travel/original-z-lite-sleeping-pad/original-z-lite.html', 'https://cdn.shopify.com/s/files/1/0574/0642/3174/files/02302_tr_zlite_coyotegray_regular_angle.jpg?v=1724820255', 'https://www.thermarest.com/sleeping-pads/trek-and-travel/original-z-lite-sleeping-pad/original-z-lite.html'),
    ('Therm-a-Rest', 'ProLite Plus Regular', 'ProLite Plus レギュラー', 'sleep', 'sleeping_pad', 652, null, 'Regular', 'Cayenne', 'https://www.thermarest.com/sleeping-pads/trek-and-travel/prolite-plus-sleeping-pad/prolite-plus.html', 'https://cdn.shopify.com/s/files/1/0574/0642/3174/files/13260_thermarest_prolite_plus_cayenne_regular_angle.jpg?v=1724820264', 'https://www.thermarest.com/sleeping-pads/trek-and-travel/prolite-plus-sleeping-pad/prolite-plus.html'),
    ('Therm-a-Rest', 'ProLite Apex Regular', 'ProLite Apex レギュラー', 'sleep', 'sleeping_pad', 624, null, 'Regular', 'Heat Wave', 'https://www.thermarest.com/sleeping-pads/trek-and-travel/prolite-apex-sleeping-pad/prolite-apex.html', 'https://cdn.shopify.com/s/files/1/0574/0642/3174/files/13256_thermarest_prolite_apex_heatwave_regular_angle.jpg?v=1724820263', 'https://www.thermarest.com/sleeping-pads/trek-and-travel/prolite-apex-sleeping-pad/prolite-apex.html'),
    ('Therm-a-Rest', 'RidgeRest Classic Regular', 'RidgeRest Classic レギュラー', 'sleep', 'sleeping_pad', 397, null, 'Regular', 'Charcoal', 'https://www.thermarest.com/sleeping-pads/trek-and-travel/ridgerest-classic-sleeping-pad/ridgerest-classic.html', 'https://cdn.shopify.com/s/files/1/0574/0642/3174/files/06432_tr_ridgerest_classic_charcoal_regular_angle.jpg?v=1724820274', 'https://www.thermarest.com/sleeping-pads/trek-and-travel/ridgerest-classic-sleeping-pad/ridgerest-classic.html')
) as v(brand, model, name_ja, category_en, subcategory_en, official_weight_grams, msrp_jpy, size, color, official_url, image_url, msrp_source_url)
join public.gear_categories c on c.name_en = v.category_en
join public.gear_subcategories s on s.category_id = c.id and s.name_en = v.subcategory_en
on conflict (brand, model) do update
set name_ja = excluded.name_ja,
    category_id = excluded.category_id,
    subcategory_id = excluded.subcategory_id,
    weight_grams = excluded.weight_grams,
    official_weight_grams = excluded.official_weight_grams,
    measured_weight_grams = excluded.measured_weight_grams,
    msrp_jpy = excluded.msrp_jpy,
    size = excluded.size,
    volume = excluded.volume,
    color = excluded.color,
    material = excluded.material,
    capacity = excluded.capacity,
    official_url = excluded.official_url,
    image_url = excluded.image_url,
    released_at = excluded.released_at,
    discontinued = excluded.discontinued,
    msrp_source_url = excluded.msrp_source_url,
    last_verified_at = excluded.last_verified_at,
    verification_status = excluded.verification_status;

insert into public.gear_product_aliases (product_id, alias)
select p.id, v.alias
from (
  values
    ('NANGA', 'オーロラテックス ライト350DX', 'AURORA TEX LIGHT 350DX'),
    ('NANGA', 'オーロラテックス ライト350DX', 'Aurora Light 350DX'),
    ('NANGA', 'オーロラテックス ライト350DX', 'NS2443-2A003015071'),
    ('NANGA', 'オーロラテックス ライト450DX', 'AURORA TEX LIGHT 450DX'),
    ('NANGA', 'オーロラテックス ライト450DX', 'Aurora Light 450DX'),
    ('NANGA', 'オーロラテックス ライト450DX', 'NS2443-2A004023071'),
    ('NANGA', 'オーロラテックス ライト600DX', 'AURORA TEX LIGHT 600DX'),
    ('NANGA', 'オーロラテックス ライト600DX', 'Aurora Light 600DX'),
    ('NANGA', 'オーロラテックス ライト750DX', 'AURORA TEX LIGHT 750DX'),
    ('NANGA', 'オーロラテックス ライト750DX', 'Aurora Light 750DX'),
    ('NANGA', 'オーロラテックス ライト900DX', 'AURORA TEX LIGHT 900DX'),
    ('NANGA', 'オーロラテックス ライト900DX', 'Aurora Light 900DX'),
    ('NANGA', 'UDD バッグ 380DX', 'UDD BAG 380DX'),
    ('NANGA', 'UDD バッグ 450DX', 'UDD BAG 450DX'),
    ('NANGA', 'UDD バッグ 450DX', 'NS2244-2A016018071'),
    ('NANGA', 'UDD バッグ 630DX', 'UDD BAG 630DX'),
    ('NANGA', 'UDD バッグ 810DX', 'UDD BAG 810DX'),
    ('NANGA', 'ミニマリスム ゼロ', 'MINIMARHYTHM ZERO'),
    ('NANGA', 'ミニマリスム 5ビロー', 'MINIMARHYTHM 5BELOW'),
    ('NANGA', 'レベル8 -13 オーロラテックス ライト', 'LEVEL8 -13 AURORA TEX LIGHT'),
    ('NANGA', 'レベル8 -13 オーロラテックス ライト', 'Level 8 -13'),
    ('ISUKA', 'エアドライト 290', 'Air Dryght 290'),
    ('ISUKA', 'エアドライト 290', 'エア ドライト 290'),
    ('ISUKA', 'エアドライト 480', 'Air Dryght 480'),
    ('ISUKA', 'エアドライト 670', 'Air Dryght 670'),
    ('ISUKA', 'エアドライト 860', 'Air Dryght 860'),
    ('ISUKA', 'エアプラス 280', 'Air Plus 280'),
    ('ISUKA', 'エアプラス 450', 'Air Plus 450'),
    ('ISUKA', 'エアプラス 630', 'Air Plus 630'),
    ('ISUKA', 'エアプラス 810', 'Air Plus 810'),
    ('ISUKA', 'アルファライト NEO 300', 'Alpha Light NEO 300'),
    ('ISUKA', 'アルファライト NEO 500', 'Alpha Light NEO 500'),
    ('ISUKA', 'ダウンプラス チロル X', 'Down Plus Tyrol X'),
    ('ISUKA', 'ダウンプラス ポカラ X', 'Down Plus Pokhara X'),
    ('NEMO', 'Tensor Trail Regular Mummy', 'Tensor Trail'),
    ('NEMO', 'Tensor Trail Regular Mummy', 'テンサー トレイル'),
    ('NEMO', 'Tensor Trail Regular Mummy', 'NEM419-007025-YEL055'),
    ('NEMO', 'Tensor Elite Regular Mummy', 'Tensor Elite'),
    ('NEMO', 'Tensor Elite Regular Mummy', 'テンサー エリート'),
    ('NEMO', 'Tensor All-Season Regular Mummy', 'Tensor All-Season'),
    ('NEMO', 'Tensor All-Season Regular Mummy', 'テンサー オールシーズン'),
    ('NEMO', 'Tensor Extreme Conditions Regular Mummy', 'Tensor Extreme Conditions'),
    ('NEMO', 'Tensor Extreme Conditions Regular Mummy', 'テンサー エクストリーム'),
    ('NEMO', 'Fillo', 'フィッロ'),
    ('NEMO', 'Fillo', 'Fillo Pillow'),
    ('NEMO', 'Fillo Elite', 'フィッロ エリート'),
    ('NEMO', 'Fillo Elite Wide', 'フィッロ エリート ワイド'),
    ('NEMO', 'Dragonfly OSMO 1P', 'Dragonfly OSMO 1P'),
    ('NEMO', 'Dragonfly OSMO 1P', 'ドラゴンフライ オズモ 1P'),
    ('NEMO', 'Dragonfly OSMO 2P', 'Dragonfly OSMO 2P'),
    ('NEMO', 'Dragonfly OSMO 2P', 'ドラゴンフライ オズモ 2P'),
    ('NEMO', 'Dragonfly OSMO 3P', 'Dragonfly OSMO 3P'),
    ('NEMO', 'Dragonfly OSMO 3P', 'ドラゴンフライ オズモ 3P'),
    ('NEMO', 'Hornet OSMO 1P', 'Hornet OSMO 1P'),
    ('NEMO', 'Hornet OSMO 1P', 'ホーネット オズモ 1P'),
    ('NEMO', 'Tani OSMO 1P', 'Tani OSMO 1P'),
    ('NEMO', 'Tani OSMO 1P', 'タニ オズモ 1P'),
    ('Therm-a-Rest', 'NeoAir XLite NXT Regular', 'NeoAir XLite NXT'),
    ('Therm-a-Rest', 'NeoAir XLite NXT Regular', 'ネオエアー XLite NXT'),
    ('Therm-a-Rest', 'NeoAir XLite NXT Regular', '14010'),
    ('Therm-a-Rest', 'NeoAir XLite NXT MAX Regular Wide', 'NeoAir XLite NXT MAX'),
    ('Therm-a-Rest', 'NeoAir XTherm NXT Regular', 'NeoAir XTherm NXT'),
    ('Therm-a-Rest', 'NeoAir XTherm NXT Regular', 'ネオエアー XTherm NXT'),
    ('Therm-a-Rest', 'NeoAir XTherm NXT MAX Regular Wide', 'NeoAir XTherm NXT MAX'),
    ('Therm-a-Rest', 'Z Lite SOL Regular', 'Z Lite SOL'),
    ('Therm-a-Rest', 'Z Lite SOL Regular', 'Zライトソル'),
    ('Therm-a-Rest', 'Original Z Lite', 'Original Z Lite'),
    ('Therm-a-Rest', 'Original Z Lite', 'Z Lite'),
    ('Therm-a-Rest', 'ProLite Plus Regular', 'ProLite Plus'),
    ('Therm-a-Rest', 'ProLite Plus Regular', 'プロライト プラス'),
    ('Therm-a-Rest', 'ProLite Apex Regular', 'ProLite Apex'),
    ('Therm-a-Rest', 'ProLite Apex Regular', 'プロライト エイペックス'),
    ('Therm-a-Rest', 'RidgeRest Classic Regular', 'RidgeRest Classic'),
    ('Therm-a-Rest', 'RidgeRest Classic Regular', 'リッジレスト クラシック')
) as v(brand, model, alias)
join public.gear_products p on p.brand = v.brand and p.model = v.model
where not exists (
  select 1
  from public.gear_product_aliases existing
  where lower(existing.alias) = lower(v.alias)
);
