insert into public.gear_subcategories (category_id, name_ja, name_en, sort_order)
select c.id, v.name_ja, v.name_en, v.sort_order
from public.gear_categories c
join (
  values
    ('clothing', 'レインジャケット', 'rain_jacket', 20),
    ('clothing', '保温着', 'insulation', 40),
    ('clothing', 'ベースレイヤー', 'base_layer', 60),
    ('clothing', 'フットウェア', 'footwear', 70),
    ('other', 'ヘルメット', 'helmet', 35),
    ('other', 'トレッキングポール', 'trekking_pole', 40),
    ('other', 'ピッケル', 'ice_axe', 45),
    ('other', '軽アイゼン・チェーンスパイク', 'traction_device', 50)
) as v(category_en, name_ja, name_en, sort_order)
on c.name_en = v.category_en
on conflict (category_id, name_en) do update
set name_ja = excluded.name_ja,
    sort_order = excluded.sort_order;

insert into public.gear_products (
  brand,
  model,
  name_ja,
  category_id,
  subcategory_id,
  weight_grams,
  official_weight_grams,
  measured_weight_grams,
  msrp_jpy,
  size,
  volume,
  color,
  material,
  capacity,
  official_url,
  image_url,
  released_at,
  discontinued,
  msrp_source_url,
  last_verified_at,
  verification_status
)
select
  v.brand,
  v.model,
  v.name_ja,
  c.id,
  s.id,
  v.official_weight_grams,
  v.official_weight_grams,
  null,
  v.msrp_jpy,
  v.size,
  v.volume,
  v.color,
  v.material,
  v.capacity,
  v.official_url,
  v.image_url,
  null,
  false,
  v.msrp_source_url,
  date '2026-06-16',
  'verified'
from (
  values
    ('山と道', 'MINI', 'MINI', 'backpack', 'backpack', 360, 36000, null, '25-32L', null, null, null, 'https://shop.yamatomichi.com/products/mini', 'https://cdns3.yamatomichi.com/wp-content/uploads/2024/08/2026_MINI_Blue-Spruce.jpg', 'https://shop.yamatomichi.com/products/mini'),
    ('山と道', 'MINI2', 'MINI2', 'backpack', 'backpack', 413, 36000, null, '25-35L', null, null, null, 'https://shop.yamatomichi.com/products/mini2', 'https://cdns3.yamatomichi.com/wp-content/uploads/2017/05/2026_MINI2_Cinnamon.jpg', 'https://shop.yamatomichi.com/products/mini2'),
    ('山と道', 'THREE', 'THREE', 'backpack', 'backpack', 554, 35000, null, null, null, null, null, 'https://shop.yamatomichi.com/products/three', 'https://cdns3.yamatomichi.com/wp-content/uploads/2019/02/2026_THREEStandard_Blue-2.jpg', 'https://shop.yamatomichi.com/products/three'),
    ('山と道', 'ONE', 'ONE', 'backpack', 'backpack', 554, 52000, null, null, null, null, null, 'https://yamatomichi.myshopify.com/products/one', 'https://cdns3.yamatomichi.com/wp-content/uploads/2024/08/square_2025_ONE_Mustard.jpg', 'https://yamatomichi.myshopify.com/products/one'),
    ('山と道', 'Yamatomichi Sacoche', 'Yamatomichi Sacoche', 'other', 'other', 46, 5500, null, null, null, null, null, 'https://shop.yamatomichi.com/products/yamatomichi-sacoche', 'https://cdns3.yamatomichi.com/wp-content/uploads/2017/05/dd533f8af1e302e609a1a028ffc49340.jpg', 'https://shop.yamatomichi.com/products/yamatomichi-sacoche'),
    ('山と道', 'Stuff Pack', 'Stuff Pack', 'other', 'other', 46, 2750, null, null, null, null, null, 'https://yamatomichi.myshopify.com/products/stuff-pack', 'https://cdns3.yamatomichi.com/wp-content/uploads/2024/08/202410_eyecatch_Stuff-Pack.jpg', 'https://yamatomichi.myshopify.com/products/stuff-pack'),
    ('山と道', 'Zip Pack', 'Zip Pack', 'other', 'other', 37, 3500, null, null, null, null, null, 'https://shop.yamatomichi.com/products/zip-pack', 'https://cdns3.yamatomichi.com/wp-content/uploads/2024/08/2026_Zip-Pack_Navy_front-1.jpg', 'https://shop.yamatomichi.com/products/zip-pack'),
    ('山と道', 'Pack Liner (3pcs.)', 'Pack Liner (3pcs.)', 'other', 'other', 42, 550, null, null, null, null, null, 'https://yamatomichi.myshopify.com/products/pack-liner', 'https://cdns3.yamatomichi.com/wp-content/uploads/2017/08/2022_Pack_Liner_eyecatch.jpg', 'https://yamatomichi.myshopify.com/products/pack-liner'),
    ('山と道', 'UL Shirt', 'UL Shirt', 'clothing', 'base_layer', 84, 12500, null, null, null, null, null, 'https://shop.yamatomichi.com/products/ul-shirt', 'https://cdns3.yamatomichi.com/wp-content/uploads/2019/07/2026_UL-Shirt_Seagrass.jpg', 'https://shop.yamatomichi.com/products/ul-shirt'),
    ('山と道', 'UL All-weather Jacket', 'UL All-weather Jacket', 'clothing', 'rain_jacket', 168, 46000, null, null, null, null, null, 'https://shop.yamatomichi.com/products/ul-all-weather-jacket', 'https://cdns3.yamatomichi.com/wp-content/uploads/2024/08/UL-All-weather-Jacket_Cinnamon-x-Blue-Gray_eyecatch.jpg', 'https://shop.yamatomichi.com/products/ul-all-weather-jacket'),
    ('山と道', 'UL All-weather Hoody', 'UL All-weather Hoody', 'clothing', 'rain_jacket', 120, 34000, null, null, null, null, null, 'https://shop.yamatomichi.com/products/ul-all-weather-hoody', 'https://cdns3.yamatomichi.com/wp-content/uploads/2018/09/a1a2556eefaac3e9d8801f485e28af16-1.jpg', 'https://shop.yamatomichi.com/products/ul-all-weather-hoody'),
    ('山と道', 'Light Alpha Vest/Jacket', 'Light Alpha Vest/Jacket', 'clothing', 'insulation', 245, 46000, null, null, null, null, null, 'https://shop.yamatomichi.com/products/light-alpha-vest-jacket', 'https://cdns3.yamatomichi.com/wp-content/uploads/2017/07/cf3d760ccfe8e0a6970b292836f91d71.jpg', 'https://shop.yamatomichi.com/products/light-alpha-vest-jacket'),
    ('finetrack', 'カミナドーム1', 'カミナドーム1', 'shelter', 'tent', 1130, null, '総重量1,280g', '本体8×15×25cm、ポール39cm', null, null, '1人用', 'https://www.finetrack.com/products/kamina-dome/', 'https://www.finetrack.com/assets/img/products/kamina-dome/im-sec1-02.jpg?v2', 'https://www.finetrack.com/products/kamina-dome/'),
    ('finetrack', 'カミナドーム2', 'カミナドーム2', 'shelter', 'tent', 1310, null, '総重量1,460g', '本体8×17×27cm、ポール39cm', null, null, '2人用', 'https://www.finetrack.com/products/kamina-dome/', 'https://www.finetrack.com/assets/img/products/kamina-dome/im-sec1-03.jpg?v2', 'https://www.finetrack.com/products/kamina-dome/'),
    ('finetrack', 'カミナドーム4', 'カミナドーム4', 'shelter', 'tent', 1860, null, '総重量2,010g', '本体9.5×18×33cm、ポール39cm', null, null, '4人用', 'https://www.finetrack.com/products/kamina-dome/', 'https://www.finetrack.com/assets/img/products/kamina-dome/im-sec1-20.png', 'https://www.finetrack.com/products/kamina-dome/'),
    ('finetrack', 'カミナモノポール1', 'カミナモノポール1', 'shelter', 'tent', 890, null, '最小重量770g', '本体5×16×24cm、ポール39cm', null, null, '1人用', 'https://www.finetrack.com/products/kamina-monopole/', 'https://www.finetrack.com/assets/img/products/kamina-monopole/im-sec2-08.png', 'https://www.finetrack.com/products/kamina-monopole/'),
    ('finetrack', 'カミナモノポール2', 'カミナモノポール2', 'shelter', 'tent', 990, null, '最小重量870g', '本体6×17×25cm、ポール39cm', null, null, '2人用', 'https://www.finetrack.com/products/kamina-monopole/', 'https://www.finetrack.com/assets/img/products/kamina-monopole/im-sec2-09.png?v2', 'https://www.finetrack.com/products/kamina-monopole/'),
    ('finetrack', 'ピコシェルター', 'ピコシェルター', 'shelter', 'tarp', 120, null, '袋込み', null, null, null, '1人用', 'https://www.finetrack.com/products/zelt/picoshelter/', 'https://www.finetrack.com/assets/img/products/items/im-FAG0121-OG.png', 'https://www.finetrack.com/products/zelt/'),
    ('finetrack', 'ツエルト1', 'ツエルト1', 'shelter', 'tarp', 230, null, '袋込み', null, null, null, '1-2人用', 'https://www.finetrack.com/products/zelt/zelt1/', 'https://www.finetrack.com/assets/img/products/items/im-FAG0122-OG.png', 'https://www.finetrack.com/products/zelt/'),
    ('finetrack', 'ツエルト2ロング', 'ツエルト2ロング', 'shelter', 'tarp', 240, null, '袋込み', null, null, null, '2-3人用', 'https://www.finetrack.com/products/zelt/zelt2long/', 'https://www.finetrack.com/assets/img/products/items/im-FAG0123-MO.png', 'https://www.finetrack.com/products/zelt/'),
    ('finetrack', 'ゴージュタープ', 'ゴージュタープ', 'shelter', 'tarp', 455, null, null, null, null, null, '2-4人用', 'https://www.finetrack.com/products/gorge-tarp/', 'https://www.finetrack.com/assets/img/ogp/og-gorge-tarp-01.png', 'https://www.finetrack.com/products/gorge-tarp/'),
    ('finetrack', 'ゴージュタープミニ', 'ゴージュタープミニ', 'shelter', 'tarp', 300, null, '収納時10×8×15cm', '280×240cm', null, null, '2-3人用', 'https://www.finetrack.com/products/gorge-tarp/', 'https://www.finetrack.com/assets/img/products/gorge-tarp/im-info-01.jpg', 'https://www.finetrack.com/products/gorge-tarp/'),
    ('Caravan', 'C1_02S', 'C1_02S', 'clothing', 'footwear', 590, 20900, '26.0cm片足標準', null, null, null, null, 'https://www.caravan-web.com/c/category/0010106', 'https://caravan.itembox.cloud/product/000/000000000007/000000000007-01.jpg?size=l&w=ODAw&t=20250822184241', 'https://www.caravan-web.com/c/category/0010106'),
    ('Caravan', 'C4_03', 'C4_03', 'clothing', 'footwear', 470, 20900, '24.0cm片足標準', null, null, null, null, 'https://www.caravan-web.com/c/category/0010403', 'https://caravan.itembox.cloud/product/000/000000000008/000000000008-01.jpg?size=l&w=ODAw&t=20250822183255', 'https://www.caravan-web.com/c/category/0010403'),
    ('Caravan', 'GK85', 'GK85', 'clothing', 'footwear', 705, 35200, '26.0cm片足標準', null, null, null, null, 'https://www.caravan-web.com/c/category/0011850', 'https://caravan.itembox.cloud/product/000/000000000069/000000000069-01.jpg?size=l&w=ODAw&t=20250822184456', 'https://www.caravan-web.com/c/category/0011850'),
    ('Caravan', 'GK8X_FFF', 'GK8X_FFF', 'clothing', 'footwear', 675, 29700, '26.0cm片足標準', null, null, null, null, 'https://www.caravan-web.com/c/category/0011897', 'https://caravan.itembox.cloud/product/009/000000000950/000000000950-01.jpg?size=l&w=ODAw&t=20250822184345', 'https://www.caravan-web.com/c/category/0011897'),
    ('Caravan', 'GK_ALT HI', 'GK_ALT HI', 'clothing', 'footwear', 605, 34650, '26.0cm片足標準', null, null, null, null, 'https://www.caravan-web.com/c/category/0011900', 'https://caravan.itembox.cloud/product/012/000000001251/000000001251-01.jpg?size=l&w=ODAw&t=20251015160248', 'https://www.caravan-web.com/c/category/0011900'),
    ('Osprey', 'ケストレル48', 'ケストレル48', 'backpack', 'backpack', 2010, 37400, 'S/M=2.01kg', '46-48L', null, null, null, 'https://www.lostarrow.co.jp/store/g/gOS50382002004/', 'https://www.lostarrow.co.jp/img/goods/S/OS50382002_S.webp', 'https://www.lostarrow.co.jp/store/g/gOS50382002004/'),
    ('Osprey', 'ケストレル38', 'ケストレル38', 'backpack', 'backpack', 1840, 34100, 'S/M=1.84kg', '36-38L', null, null, null, 'https://www.lostarrow.co.jp/store/g/gOS50383003004/', 'https://www.lostarrow.co.jp/img/goods/S/OS50383003_S.webp', 'https://www.lostarrow.co.jp/store/g/gOS50383003004/'),
    ('Osprey', 'ケストレルLT45', 'ケストレルLT45', 'backpack', 'backpack', 1830, 31900, null, '45L', null, null, null, 'https://www.lostarrow.co.jp/store/g/gOS50158001/', 'https://www.lostarrow.co.jp/img/goods/S/OS50158001_S.webp', 'https://www.lostarrow.co.jp/store/g/gOS50158001/'),
    ('Osprey', 'ケストレルLT35', 'ケストレルLT35', 'backpack', 'backpack', 1450, 28600, null, '35L', null, null, null, 'https://www.lostarrow.co.jp/store/g/gOS50159001/', 'https://www.lostarrow.co.jp/img/goods/S/OS50159001_S.webp', 'https://www.lostarrow.co.jp/store/g/gOS50159001/'),
    ('Osprey', 'エクソスプロ55', 'エクソスプロ55', 'backpack', 'backpack', 960, 49500, 'S/M', '55L', null, null, null, 'https://www.lostarrow.co.jp/store/g/gOS50380001004/', 'https://www.lostarrow.co.jp/img/goods/S/OS50380001_S.webp', 'https://www.lostarrow.co.jp/store/g/gOS50380001004/'),
    ('Osprey', 'タロンプロ40', 'タロンプロ40', 'backpack', 'backpack', 1440, 44000, 'S/M', '40L', null, null, null, 'https://www.lostarrow.co.jp/store/g/gOS50271001004/', 'https://www.lostarrow.co.jp/img/goods/S/OS50271001_S.webp', 'https://www.lostarrow.co.jp/store/g/gOS50271001004/'),
    ('Osprey', 'タロンベロシティ20', 'タロンベロシティ20', 'backpack', 'backpack', 870, 30800, 'S/M', '20L', null, null, null, 'https://www.lostarrow.co.jp/store/g/gOS50268001004/', 'https://www.lostarrow.co.jp/img/goods/S/OS50268001_S.webp', 'https://www.lostarrow.co.jp/store/g/gOS50268001004/'),
    ('Osprey', 'テンペストベロシティ20', 'テンペストベロシティ20', 'backpack', 'backpack', 820, 30800, 'WXS/S', '18-20L', null, null, null, 'https://www.lostarrow.co.jp/store/g/gOS50270001004/', 'https://www.lostarrow.co.jp/img/goods/S/OS50270001_S.webp', 'https://www.lostarrow.co.jp/store/g/gOS50270001004/'),
    ('Petzl', 'ACTIK CORE', 'ACTIK CORE', 'electronics', 'headlamp', 88, null, '625 lumens', null, null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps/ACTIK-CORE', 'https://www.petzl.com/sfc/servlet.shepherd/version/download/068Tx000006KwpEIAS', 'https://www.petzl.com/INT/en/Sport/Headlamps/ACTIK-CORE'),
    ('Petzl', 'ACTIK', 'ACTIK', 'electronics', 'headlamp', 98, null, '450 lumens', null, null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps/ACTIK', 'https://www.petzl.com/sfc/servlet.shepherd/version/download/068Tx000006KdoHIAS', 'https://www.petzl.com/INT/en/Sport/Headlamps/ACTIK'),
    ('Petzl', 'TIKKA CORE', 'TIKKA CORE', 'electronics', 'headlamp', 84, null, '450 lumens', null, null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps/TIKKA-CORE', 'https://www.petzl.com/sfc/servlet.shepherd/version/download/068Tx000006L5ZAIA0', 'https://www.petzl.com/INT/en/Sport/Headlamps/TIKKA-CORE'),
    ('Petzl', 'TIKKA', 'TIKKA', 'electronics', 'headlamp', 94, null, '350 lumens', null, null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps/TIKKA', 'https://www.petzl.com/sfc/servlet.shepherd/version/download/068Tx00000BWDtTIAX', 'https://www.petzl.com/INT/en/Sport/Headlamps/TIKKA'),
    ('Petzl', 'SWIFT RL', 'SWIFT RL', 'electronics', 'headlamp', 92, null, '1200 lumens', null, null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps/SWIFT-RL', 'https://www.petzl.com/sfc/servlet.shepherd/version/download/068Tx00000DjjT2IAJ', 'https://www.petzl.com/INT/en/Sport/Headlamps/SWIFT-RL'),
    ('Petzl', 'IKO CORE', 'IKO CORE', 'electronics', 'headlamp', 79, null, '500 lumens', null, null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps/IKO-CORE', 'https://www.petzl.com/sfc/servlet.shepherd/version/download/068bK00000g2zqTQAQ', 'https://www.petzl.com/INT/en/Sport/Headlamps/IKO-CORE')
) as v(brand, model, name_ja, category_en, subcategory_en, official_weight_grams, msrp_jpy, size, volume, color, material, capacity, official_url, image_url, msrp_source_url)
join public.gear_categories c on c.name_en = v.category_en
join public.gear_subcategories s on s.category_id = c.id and s.name_en = v.subcategory_en
on conflict (brand, model) do update
set name_ja = excluded.name_ja,
    category_id = excluded.category_id,
    subcategory_id = excluded.subcategory_id,
    weight_grams = excluded.weight_grams,
    official_weight_grams = excluded.official_weight_grams,
    measured_weight_grams = excluded.measured_weight_grams,
    msrp_jpy = excluded.msrp_jpy,
    size = excluded.size,
    volume = excluded.volume,
    color = excluded.color,
    material = excluded.material,
    capacity = excluded.capacity,
    official_url = excluded.official_url,
    image_url = excluded.image_url,
    released_at = excluded.released_at,
    discontinued = excluded.discontinued,
    msrp_source_url = excluded.msrp_source_url,
    last_verified_at = excluded.last_verified_at,
    verification_status = excluded.verification_status;

insert into public.gear_product_aliases (product_id, alias)
select p.id, v.alias
from (
  values
    ('山と道', 'MINI', 'Yamatomichi MINI'),
    ('山と道', 'MINI', '山と道 MINI'),
    ('山と道', 'MINI', '山道 MINI'),
    ('山と道', 'MINI2', 'Yamatomichi MINI2'),
    ('山と道', 'MINI2', '山と道 MINI2'),
    ('山と道', 'MINI2', '山道 MINI2'),
    ('山と道', 'THREE', 'Yamatomichi THREE'),
    ('山と道', 'THREE', '山と道 THREE'),
    ('山と道', 'ONE', 'Yamatomichi ONE'),
    ('山と道', 'ONE', '山と道 ONE'),
    ('山と道', 'Yamatomichi Sacoche', '山と道 サコッシュ'),
    ('山と道', 'Yamatomichi Sacoche', 'サコッシュ'),
    ('山と道', 'Stuff Pack', 'スタッフパック'),
    ('山と道', 'Zip Pack', 'ジップパック'),
    ('山と道', 'Pack Liner (3pcs.)', 'パックライナー'),
    ('山と道', 'UL Shirt', 'ULシャツ'),
    ('山と道', 'UL All-weather Jacket', 'ULオールウェザージャケット'),
    ('山と道', 'UL All-weather Hoody', 'ULオールウェザーフーディ'),
    ('山と道', 'Light Alpha Vest/Jacket', 'ライトアルファ'),
    ('finetrack', 'カミナドーム1', 'KAMINA DOME 1'),
    ('finetrack', 'カミナドーム1', 'FAG0311'),
    ('finetrack', 'カミナドーム2', 'KAMINA DOME 2'),
    ('finetrack', 'カミナドーム2', 'FAG0312'),
    ('finetrack', 'カミナドーム4', 'KAMINA DOME 4'),
    ('finetrack', 'カミナドーム4', 'FAG0314'),
    ('finetrack', 'カミナモノポール1', 'KAMINA MONOPOLE 1'),
    ('finetrack', 'カミナモノポール1', 'FAG0601'),
    ('finetrack', 'カミナモノポール2', 'KAMINA MONOPOLE 2'),
    ('finetrack', 'カミナモノポール2', 'FAG0602'),
    ('finetrack', 'ピコシェルター', 'Pico Shelter'),
    ('finetrack', 'ピコシェルター', 'FAG0121'),
    ('finetrack', 'ツエルト1', 'Zelt 1'),
    ('finetrack', 'ツエルト1', 'FAG0122'),
    ('finetrack', 'ツエルト2ロング', 'Zelt 2 Long'),
    ('finetrack', 'ツエルト2ロング', 'FAG0123'),
    ('finetrack', 'ゴージュタープ', 'Gorge Tarp'),
    ('finetrack', 'ゴージュタープミニ', 'Gorge Tarp Mini'),
    ('Caravan', 'C1_02S', 'キャラバン C1_02S'),
    ('Caravan', 'C4_03', 'キャラバン C4_03'),
    ('Caravan', 'GK85', 'GRANDKING GK85'),
    ('Caravan', 'GK8X_FFF', 'GRANDKING GK8X FFF'),
    ('Caravan', 'GK_ALT HI', 'GRANDKING GK ALT HI'),
    ('Osprey', 'ケストレル48', 'Kestrel 48'),
    ('Osprey', 'ケストレル38', 'Kestrel 38'),
    ('Osprey', 'ケストレルLT45', 'Kestrel LT 45'),
    ('Osprey', 'ケストレルLT35', 'Kestrel LT 35'),
    ('Osprey', 'エクソスプロ55', 'Exos Pro 55'),
    ('Osprey', 'タロンプロ40', 'Talon Pro 40'),
    ('Osprey', 'タロンベロシティ20', 'Talon Velocity 20'),
    ('Osprey', 'テンペストベロシティ20', 'Tempest Velocity 20'),
    ('Petzl', 'ACTIK CORE', 'アクティック コア'),
    ('Petzl', 'ACTIK', 'アクティック'),
    ('Petzl', 'TIKKA CORE', 'ティカ コア'),
    ('Petzl', 'TIKKA', 'ティカ'),
    ('Petzl', 'SWIFT RL', 'スイフト RL'),
    ('Petzl', 'IKO CORE', 'イコ コア'),
    ('Garmin', 'eTrex SE', 'ガーミン eTrex SE'),
    ('Garmin', 'eTrex SE', 'イートレックス SE'),
    ('EVERNEW', 'Ti 570FD Cup', 'エバニュー Ti 570FD Cup'),
    ('EVERNEW', 'Ti 570FD Cup', 'EBY274')
) as v(brand, model, alias)
join public.gear_products p on p.brand = v.brand and p.model = v.model
where not exists (
  select 1
  from public.gear_product_aliases existing
  where lower(existing.alias) = lower(v.alias)
);
