insert into public.gear_subcategories (category_id, name_ja, name_en, sort_order)
select c.id, v.name_ja, v.name_en, v.sort_order
from public.gear_categories c
join (
  values
    ('clothing', '帽子', 'hat', 85),
    ('clothing', 'ゲイター', 'gaiters', 90),
    ('other', 'ヘルメット', 'helmet', 35)
) as v(category_en, name_ja, name_en, sort_order)
on c.name_en = v.category_en
on conflict (category_id, name_en) do update
set name_ja = excluded.name_ja,
    sort_order = excluded.sort_order;

insert into public.gear_products (
  brand,
  model,
  name_ja,
  category_id,
  subcategory_id,
  weight_grams,
  official_weight_grams,
  measured_weight_grams,
  msrp_jpy,
  size,
  volume,
  color,
  material,
  capacity,
  official_url,
  image_url,
  released_at,
  discontinued,
  msrp_source_url,
  last_verified_at,
  verification_status
)
select
  v.brand,
  v.model,
  v.name_ja,
  c.id,
  s.id,
  null,
  null,
  null,
  null,
  v.size,
  v.volume,
  null,
  null,
  v.capacity,
  v.official_url,
  null,
  null,
  false,
  v.official_url,
  date '2026-06-21',
  'needs_review'
from (
  values
    ('山と道', '5-Pocket Pants', '5-Pocket Pants', 'clothing', 'base_layer', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', '5-Pocket Shorts', '5-Pocket Shorts', 'clothing', 'base_layer', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', 'Light 5-Pocket Pants', 'Light 5-Pocket Pants', 'clothing', 'base_layer', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', 'DW 5-Pocket Pants', 'DW 5-Pocket Pants', 'clothing', 'base_layer', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', '100% Merino Light Long Sleeve', '100% Merino Light Long Sleeve', 'clothing', 'base_layer', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', '100% Merino Hoody', '100% Merino Hoody', 'clothing', 'base_layer', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', 'Bamboo Shirt', 'Bamboo Shirt', 'clothing', 'base_layer', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', 'UL Short Sleeve Shirt', 'UL Short Sleeve Shirt', 'clothing', 'base_layer', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', 'Alpha Anorak', 'Alpha Anorak', 'clothing', 'insulation', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', 'Light Alpha Tights', 'Light Alpha Tights', 'clothing', 'insulation', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', 'UL All-weather Pants', 'UL All-weather Pants', 'clothing', 'rain_pants', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', 'Light Rain Jacket', 'Light Rain Jacket', 'clothing', 'rain_jacket', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', 'Only Hood', 'Only Hood', 'other', 'other', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', 'Merino Knit Cap', 'Merino Knit Cap', 'clothing', 'hat', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('山と道', 'Alpha Haramaki', 'Alpha Haramaki', 'other', 'other', null, null, null, 'https://shop.yamatomichi.com/collections/all'),
    ('finetrack', 'ドライレイヤーベーシックT', 'ドライレイヤーベーシックT', 'clothing', 'base_layer', null, null, null, 'https://www.finetrack.com/products/'),
    ('finetrack', 'ドライレイヤークールT', 'ドライレイヤークールT', 'clothing', 'base_layer', null, null, null, 'https://www.finetrack.com/products/'),
    ('finetrack', 'ドライレイヤーウォームロングスリーブ', 'ドライレイヤーウォームロングスリーブ', 'clothing', 'base_layer', null, null, null, 'https://www.finetrack.com/products/'),
    ('finetrack', 'メリノスピンライトロングスリーブ', 'メリノスピンライトロングスリーブ', 'clothing', 'base_layer', null, null, null, 'https://www.finetrack.com/products/'),
    ('finetrack', 'エバーブレスフォトンジャケット', 'エバーブレスフォトンジャケット', 'clothing', 'rain_jacket', null, null, null, 'https://www.finetrack.com/products/'),
    ('finetrack', 'エバーブレスフォトンパンツ', 'エバーブレスフォトンパンツ', 'clothing', 'rain_pants', null, null, null, 'https://www.finetrack.com/products/'),
    ('finetrack', 'フロウラップフーディ', 'フロウラップフーディ', 'clothing', 'insulation', null, null, null, 'https://www.finetrack.com/products/'),
    ('finetrack', 'ポリゴンULジャケット', 'ポリゴンULジャケット', 'clothing', 'insulation', null, null, null, 'https://www.finetrack.com/products/'),
    ('finetrack', 'ドラウトクロージャケット', 'ドラウトクロージャケット', 'clothing', 'insulation', null, null, null, 'https://www.finetrack.com/products/'),
    ('finetrack', 'カミノパンツ', 'カミノパンツ', 'clothing', 'base_layer', null, null, null, 'https://www.finetrack.com/products/'),
    ('finetrack', 'ストームゴージュアルパインパンツ', 'ストームゴージュアルパインパンツ', 'clothing', 'rain_pants', null, null, null, 'https://www.finetrack.com/products/'),
    ('finetrack', 'カミナドーム1 フットプリント', 'カミナドーム1 フットプリント', 'shelter', 'groundsheet', null, null, null, 'https://www.finetrack.com/products/kamina-dome/'),
    ('finetrack', 'カミナドーム2 フットプリント', 'カミナドーム2 フットプリント', 'shelter', 'groundsheet', null, null, null, 'https://www.finetrack.com/products/kamina-dome/'),
    ('finetrack', 'ツエルト2', 'ツエルト2', 'shelter', 'tarp', null, null, null, 'https://www.finetrack.com/products/zelt/'),
    ('finetrack', 'ナノタオル', 'ナノタオル', 'other', 'other', null, null, null, 'https://www.finetrack.com/products/'),
    ('Caravan', 'C1_LIGHT MID', 'C1_LIGHT MID', 'clothing', 'footwear', null, null, null, 'https://www.caravan-web.com/c/category'),
    ('Caravan', 'C1_LIGHT LOW', 'C1_LIGHT LOW', 'clothing', 'footwear', null, null, null, 'https://www.caravan-web.com/c/category'),
    ('Caravan', 'C7_04', 'C7_04', 'clothing', 'footwear', null, null, null, 'https://www.caravan-web.com/c/category'),
    ('Caravan', 'C6_02', 'C6_02', 'clothing', 'footwear', null, null, null, 'https://www.caravan-web.com/c/category'),
    ('Caravan', 'GK83', 'GK83', 'clothing', 'footwear', null, null, null, 'https://www.caravan-web.com/c/category'),
    ('Caravan', 'GK88', 'GK88', 'clothing', 'footwear', null, null, null, 'https://www.caravan-web.com/c/category'),
    ('Caravan', 'GK26', 'GK26', 'clothing', 'footwear', null, null, null, 'https://www.caravan-web.com/c/category'),
    ('Caravan', 'GK10', 'GK10', 'clothing', 'footwear', null, null, null, 'https://www.caravan-web.com/c/category'),
    ('Caravan', 'KR_3XF', 'KR_3XF', 'clothing', 'footwear', null, null, null, 'https://www.caravan-web.com/c/category'),
    ('Caravan', 'KR_3XR', 'KR_3XR', 'clothing', 'footwear', null, null, null, 'https://www.caravan-web.com/c/category'),
    ('Caravan', 'SHC_10', 'SHC_10', 'clothing', 'footwear', null, null, null, 'https://www.caravan-web.com/c/category'),
    ('Caravan', '渓流 KR_3XFW', '渓流 KR_3XFW', 'clothing', 'footwear', null, null, null, 'https://www.caravan-web.com/c/category'),
    ('Osprey', 'タロン22', 'タロン22', 'backpack', 'backpack', null, '22L', null, 'https://www.osprey.com/'),
    ('Osprey', 'タロン33', 'タロン33', 'backpack', 'backpack', null, '33L', null, 'https://www.osprey.com/'),
    ('Osprey', 'タロン44', 'タロン44', 'backpack', 'backpack', null, '44L', null, 'https://www.osprey.com/'),
    ('Osprey', 'テンペスト20', 'テンペスト20', 'backpack', 'backpack', null, '20L', null, 'https://www.osprey.com/'),
    ('Osprey', 'テンペスト30', 'テンペスト30', 'backpack', 'backpack', null, '30L', null, 'https://www.osprey.com/'),
    ('Osprey', 'ストラトス26', 'ストラトス26', 'backpack', 'backpack', null, '26L', null, 'https://www.osprey.com/'),
    ('Osprey', 'ストラトス36', 'ストラトス36', 'backpack', 'backpack', null, '36L', null, 'https://www.osprey.com/'),
    ('Osprey', 'シラス26', 'シラス26', 'backpack', 'backpack', null, '26L', null, 'https://www.osprey.com/'),
    ('Osprey', 'シラス36', 'シラス36', 'backpack', 'backpack', null, '36L', null, 'https://www.osprey.com/'),
    ('Osprey', 'ハイクライト18', 'ハイクライト18', 'backpack', 'backpack', null, '18L', null, 'https://www.osprey.com/'),
    ('Osprey', 'ハイクライト26', 'ハイクライト26', 'backpack', 'backpack', null, '26L', null, 'https://www.osprey.com/'),
    ('Osprey', 'エクソス48', 'エクソス48', 'backpack', 'backpack', null, '48L', null, 'https://www.osprey.com/'),
    ('Osprey', 'エイジャ48', 'エイジャ48', 'backpack', 'backpack', null, '48L', null, 'https://www.osprey.com/'),
    ('Osprey', 'ミュータント38', 'ミュータント38', 'backpack', 'backpack', null, '38L', null, 'https://www.osprey.com/'),
    ('Petzl', 'BINDI', 'BINDI', 'electronics', 'headlamp', null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps'),
    ('Petzl', 'ARIA 1 RGB', 'ARIA 1 RGB', 'electronics', 'headlamp', null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps'),
    ('Petzl', 'ARIA 2 RGB', 'ARIA 2 RGB', 'electronics', 'headlamp', null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps'),
    ('Petzl', 'ARIA 2R', 'ARIA 2R', 'electronics', 'headlamp', null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps'),
    ('Petzl', 'NAO RL', 'NAO RL', 'electronics', 'headlamp', null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps'),
    ('Petzl', 'TACTIKKA', 'TACTIKKA', 'electronics', 'headlamp', null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps'),
    ('Petzl', 'TACTIKKA CORE', 'TACTIKKA CORE', 'electronics', 'headlamp', null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps'),
    ('Petzl', 'IKO', 'IKO', 'electronics', 'headlamp', null, null, null, 'https://www.petzl.com/INT/en/Sport/Headlamps'),
    ('Petzl', 'BOREO', 'BOREO', 'other', 'helmet', null, null, null, 'https://www.petzl.com/INT/en/Sport/Helmets'),
    ('Petzl', 'METEOR', 'METEOR', 'other', 'helmet', null, null, null, 'https://www.petzl.com/INT/en/Sport/Helmets')
) as v(brand, model, name_ja, category_en, subcategory_en, size, volume, capacity, official_url)
join public.gear_categories c on c.name_en = v.category_en
join public.gear_subcategories s on s.category_id = c.id and s.name_en = v.subcategory_en
on conflict (brand, model) do update
set name_ja = excluded.name_ja,
    category_id = excluded.category_id,
    subcategory_id = excluded.subcategory_id,
    size = excluded.size,
    volume = excluded.volume,
    capacity = excluded.capacity,
    official_url = excluded.official_url,
    msrp_source_url = excluded.msrp_source_url,
    discontinued = false,
    verification_status = case
      when public.gear_products.verification_status = 'verified' then public.gear_products.verification_status
      else excluded.verification_status
    end;

insert into public.gear_product_aliases (product_id, alias)
select p.id, v.alias
from (
  values
    ('山と道', '5-Pocket Pants', '山と道 5-Pocket Pants'),
    ('山と道', '5-Pocket Shorts', '山と道 5-Pocket Shorts'),
    ('山と道', 'Light 5-Pocket Pants', 'ライト5ポケットパンツ'),
    ('山と道', 'DW 5-Pocket Pants', 'DW 5ポケットパンツ'),
    ('山と道', '100% Merino Light Long Sleeve', 'メリノライトロングスリーブ'),
    ('山と道', '100% Merino Hoody', 'メリノフーディ'),
    ('山と道', 'Bamboo Shirt', 'バンブーシャツ'),
    ('山と道', 'UL Short Sleeve Shirt', 'ULショートスリーブシャツ'),
    ('山と道', 'Alpha Anorak', 'アルファアノラック'),
    ('山と道', 'Light Alpha Tights', 'ライトアルファタイツ'),
    ('山と道', 'UL All-weather Pants', 'ULオールウェザーパンツ'),
    ('山と道', 'Light Rain Jacket', 'ライトレインジャケット'),
    ('山と道', 'Only Hood', 'オンリーフード'),
    ('山と道', 'Merino Knit Cap', 'メリノニットキャップ'),
    ('山と道', 'Alpha Haramaki', 'アルファ腹巻'),
    ('finetrack', 'ドライレイヤーベーシックT', 'Dry Layer Basic T'),
    ('finetrack', 'ドライレイヤークールT', 'Dry Layer Cool T'),
    ('finetrack', 'ドライレイヤーウォームロングスリーブ', 'Dry Layer Warm Long Sleeve'),
    ('finetrack', 'メリノスピンライトロングスリーブ', 'Merino Spin Light Long Sleeve'),
    ('finetrack', 'エバーブレスフォトンジャケット', 'Everbreath Photon Jacket'),
    ('finetrack', 'エバーブレスフォトンパンツ', 'Everbreath Photon Pants'),
    ('finetrack', 'フロウラップフーディ', 'Flow Wrap Hoodie'),
    ('finetrack', 'ポリゴンULジャケット', 'Polygon UL Jacket'),
    ('finetrack', 'ドラウトクロージャケット', 'Drought Claw Jacket'),
    ('finetrack', 'カミノパンツ', 'Camino Pants'),
    ('finetrack', 'ストームゴージュアルパインパンツ', 'Storm Gorge Alpine Pants'),
    ('finetrack', 'カミナドーム1 フットプリント', 'Kamina Dome 1 Footprint'),
    ('finetrack', 'カミナドーム2 フットプリント', 'Kamina Dome 2 Footprint'),
    ('finetrack', 'ツエルト2', 'Zelt 2'),
    ('finetrack', 'ナノタオル', 'Nano Towel'),
    ('Caravan', 'C1_LIGHT MID', 'キャラバン C1 LIGHT MID'),
    ('Caravan', 'C1_LIGHT LOW', 'キャラバン C1 LIGHT LOW'),
    ('Caravan', 'C7_04', 'キャラバン C7_04'),
    ('Caravan', 'C6_02', 'キャラバン C6_02'),
    ('Caravan', 'GK83', 'GRANDKING GK83'),
    ('Caravan', 'GK88', 'GRANDKING GK88'),
    ('Caravan', 'GK26', 'GRANDKING GK26'),
    ('Caravan', 'GK10', 'GRANDKING GK10'),
    ('Caravan', 'KR_3XF', 'キャラバン KR_3XF'),
    ('Caravan', 'KR_3XR', 'キャラバン KR_3XR'),
    ('Caravan', 'SHC_10', 'キャラバン SHC_10'),
    ('Caravan', '渓流 KR_3XFW', '渓流 KR_3XFW'),
    ('Osprey', 'タロン22', 'Talon 22'),
    ('Osprey', 'タロン33', 'Talon 33'),
    ('Osprey', 'タロン44', 'Talon 44'),
    ('Osprey', 'テンペスト20', 'Tempest 20'),
    ('Osprey', 'テンペスト30', 'Tempest 30'),
    ('Osprey', 'ストラトス26', 'Stratos 26'),
    ('Osprey', 'ストラトス36', 'Stratos 36'),
    ('Osprey', 'シラス26', 'Sirrus 26'),
    ('Osprey', 'シラス36', 'Sirrus 36'),
    ('Osprey', 'ハイクライト18', 'Hikelite 18'),
    ('Osprey', 'ハイクライト26', 'Hikelite 26'),
    ('Osprey', 'エクソス48', 'Exos 48'),
    ('Osprey', 'エイジャ48', 'Eja 48'),
    ('Osprey', 'ミュータント38', 'Mutant 38'),
    ('Petzl', 'BINDI', 'ビンディ'),
    ('Petzl', 'ARIA 1 RGB', 'アリア 1 RGB'),
    ('Petzl', 'ARIA 2 RGB', 'アリア 2 RGB'),
    ('Petzl', 'ARIA 2R', 'アリア 2R'),
    ('Petzl', 'NAO RL', 'ナオ RL'),
    ('Petzl', 'TACTIKKA', 'タクティカ'),
    ('Petzl', 'TACTIKKA CORE', 'タクティカ コア'),
    ('Petzl', 'IKO', 'イコ'),
    ('Petzl', 'BOREO', 'ボレオ'),
    ('Petzl', 'METEOR', 'メテオ')
) as v(brand, model, alias)
join public.gear_products p on p.brand = v.brand and p.model = v.model
where not exists (
  select 1
  from public.gear_product_aliases existing
  where lower(existing.alias) = lower(v.alias)
);
