insert into public.gear_subcategories (category_id, name_ja, name_en, sort_order)
select c.id, v.name_ja, v.name_en, v.sort_order
from public.gear_categories c
join (
  values
    ('clothing', '登山靴', 'footwear', 70)
) as v(category_en, name_ja, name_en, sort_order)
on c.name_en = v.category_en
on conflict (category_id, name_en) do update
set name_ja = excluded.name_ja,
    sort_order = excluded.sort_order;

insert into public.gear_products (
  brand,
  model,
  name_ja,
  category_id,
  subcategory_id,
  weight_grams,
  official_weight_grams,
  measured_weight_grams,
  msrp_jpy,
  size,
  volume,
  color,
  material,
  capacity,
  official_url,
  image_url,
  released_at,
  discontinued,
  msrp_source_url,
  last_verified_at,
  verification_status
)
select
  v.brand,
  v.model,
  v.name_ja,
  c.id,
  s.id,
  null,
  null,
  null,
  null,
  null,
  v.volume,
  null,
  null,
  null,
  v.official_url,
  null,
  null,
  false,
  v.official_url,
  date '2026-06-21',
  'needs_review'
from (
  values
    ('Columbia', 'Saber Five Mid Outdry', 'セイバー ファイブ ミッド アウトドライ', 'clothing', 'footwear', null, 'https://www.columbiasports.co.jp/'),
    ('Columbia', 'Saber Five Low Outdry', 'セイバー ファイブ ロウ アウトドライ', 'clothing', 'footwear', null, 'https://www.columbiasports.co.jp/'),
    ('Columbia', 'Peakfreak II Outdry', 'ピークフリーク II アウトドライ', 'clothing', 'footwear', null, 'https://www.columbiasports.co.jp/'),
    ('Columbia', 'Hazy Journey Waterproof', 'ヘイジージャーニー ウォータープルーフ', 'clothing', 'footwear', null, 'https://www.columbiasports.co.jp/'),
    ('Columbia', 'Wabash Jacket', 'ワバシュ ジャケット', 'clothing', 'rain_jacket', null, 'https://www.columbiasports.co.jp/'),
    ('Columbia', 'Light Canyon Softshell', 'ライトキャニオン ソフトシェル', 'clothing', 'insulation', null, 'https://www.columbiasports.co.jp/'),
    ('Columbia', 'Vizzavona Pass Jacket', 'ヴィザボナパス ジャケット', 'clothing', 'rain_jacket', null, 'https://www.columbiasports.co.jp/'),
    ('Columbia', 'Mountains Are Calling Jacket', 'マウンテンズアーコーリング ジャケット', 'clothing', 'rain_jacket', null, 'https://www.columbiasports.co.jp/'),
    ('Columbia', 'Blue Ridge Mountain 30L', 'ブルーリッジマウンテン 30L', 'backpack', 'backpack', '30L', 'https://www.columbiasports.co.jp/'),
    ('Columbia', 'Castle Rock 25L', 'キャッスルロック 25L', 'backpack', 'backpack', '25L', 'https://www.columbiasports.co.jp/'),
    ('MILLET', 'SAAS FEE NX 30+5', 'サースフェー NX 30+5', 'backpack', 'backpack', '30+5L', 'https://www.millet.jp/'),
    ('MILLET', 'SAAS FEE NX 40+5', 'サースフェー NX 40+5', 'backpack', 'backpack', '40+5L', 'https://www.millet.jp/'),
    ('MILLET', 'KULA 30', 'クーラ 30', 'backpack', 'backpack', '30L', 'https://www.millet.jp/'),
    ('MILLET', 'WELKIN 30', 'ウェルキン 30', 'backpack', 'backpack', '30L', 'https://www.millet.jp/'),
    ('MILLET', 'TYPHON 50000 Stretch Jacket', 'ティフォン 50000 ストレッチ ジャケット', 'clothing', 'rain_jacket', null, 'https://www.millet.jp/'),
    ('MILLET', 'TYPHON 50000 Stretch Pants', 'ティフォン 50000 ストレッチ パンツ', 'clothing', 'rain_pants', null, 'https://www.millet.jp/'),
    ('MILLET', 'Drynamic Mesh NS', 'ドライナミック メッシュ NS', 'clothing', 'base_layer', null, 'https://www.millet.jp/'),
    ('MILLET', 'Drynamic Mesh 3/4 Tights', 'ドライナミック メッシュ 3/4 タイツ', 'clothing', 'base_layer', null, 'https://www.millet.jp/'),
    ('MILLET', 'Breathe Barrier Toi Alpha Direct Jacket', 'ブリーズバリヤー トイ アルファ ダイレクト ジャケット', 'clothing', 'insulation', null, 'https://www.millet.jp/'),
    ('MILLET', 'Wanaka Stretch Pants', 'ワナカ ストレッチ パンツ', 'clothing', 'base_layer', null, 'https://www.millet.jp/'),
    ('Arc''teryx', 'Beta Jacket', 'Beta Jacket', 'clothing', 'rain_jacket', null, 'https://arcteryx.jp/'),
    ('Arc''teryx', 'Beta AR Jacket', 'Beta AR Jacket', 'clothing', 'rain_jacket', null, 'https://arcteryx.jp/'),
    ('Arc''teryx', 'Alpha SV Jacket', 'Alpha SV Jacket', 'clothing', 'rain_jacket', null, 'https://arcteryx.jp/'),
    ('Arc''teryx', 'Atom Hoody', 'Atom Hoody', 'clothing', 'insulation', null, 'https://arcteryx.jp/'),
    ('Arc''teryx', 'Proton Hoody', 'Proton Hoody', 'clothing', 'insulation', null, 'https://arcteryx.jp/'),
    ('Arc''teryx', 'Cerium Hoody', 'Cerium Hoody', 'clothing', 'down_jacket', null, 'https://arcteryx.jp/'),
    ('Arc''teryx', 'Kyanite Hoody', 'Kyanite Hoody', 'clothing', 'insulation', null, 'https://arcteryx.jp/'),
    ('Arc''teryx', 'Gamma Pant', 'Gamma Pant', 'clothing', 'base_layer', null, 'https://arcteryx.jp/'),
    ('Arc''teryx', 'Aerios FL 2 GTX', 'Aerios FL 2 GTX', 'clothing', 'footwear', null, 'https://arcteryx.jp/'),
    ('Arc''teryx', 'Bora 65', 'Bora 65', 'backpack', 'backpack', '65L', 'https://arcteryx.jp/'),
    ('patagonia', 'Torrentshell 3L Jacket', 'トレントシェル 3L ジャケット', 'clothing', 'rain_jacket', null, 'https://www.patagonia.jp/'),
    ('patagonia', 'Torrentshell 3L Pants', 'トレントシェル 3L パンツ', 'clothing', 'rain_pants', null, 'https://www.patagonia.jp/'),
    ('patagonia', 'Houdini Jacket', 'フーディニ ジャケット', 'clothing', 'rain_jacket', null, 'https://www.patagonia.jp/'),
    ('patagonia', 'R1 Air Zip-Neck', 'R1 Air Zip-Neck', 'clothing', 'base_layer', null, 'https://www.patagonia.jp/'),
    ('patagonia', 'R1 Air Hoody', 'R1 Air Hoody', 'clothing', 'insulation', null, 'https://www.patagonia.jp/'),
    ('patagonia', 'Nano Puff Jacket', 'ナノ・パフ・ジャケット', 'clothing', 'insulation', null, 'https://www.patagonia.jp/'),
    ('patagonia', 'Down Sweater Hoody', 'ダウン・セーター・フーディ', 'clothing', 'down_jacket', null, 'https://www.patagonia.jp/'),
    ('patagonia', 'Capilene Cool Daily Shirt', 'キャプリーン・クール・デイリー・シャツ', 'clothing', 'base_layer', null, 'https://www.patagonia.jp/'),
    ('patagonia', 'Terrebonne Joggers', 'テルボンヌ・ジョガーズ', 'clothing', 'base_layer', null, 'https://www.patagonia.jp/'),
    ('patagonia', 'Black Hole Pack 32L', 'ブラックホール・パック 32L', 'backpack', 'backpack', '32L', 'https://www.patagonia.jp/'),
    ('GREGORY', 'Zulu 30', 'ズール 30', 'backpack', 'backpack', '30L', 'https://www.gregory.jp/'),
    ('GREGORY', 'Zulu 35', 'ズール 35', 'backpack', 'backpack', '35L', 'https://www.gregory.jp/'),
    ('GREGORY', 'Zulu 45', 'ズール 45', 'backpack', 'backpack', '45L', 'https://www.gregory.jp/'),
    ('GREGORY', 'Jade 28', 'ジェイド 28', 'backpack', 'backpack', '28L', 'https://www.gregory.jp/'),
    ('GREGORY', 'Jade 38', 'ジェイド 38', 'backpack', 'backpack', '38L', 'https://www.gregory.jp/'),
    ('GREGORY', 'Baltoro 65', 'バルトロ 65', 'backpack', 'backpack', '65L', 'https://www.gregory.jp/'),
    ('GREGORY', 'Deva 60', 'ディバ 60', 'backpack', 'backpack', '60L', 'https://www.gregory.jp/'),
    ('GREGORY', 'Paragon 48', 'パラゴン 48', 'backpack', 'backpack', '48L', 'https://www.gregory.jp/'),
    ('GREGORY', 'Maven 45', 'メイブン 45', 'backpack', 'backpack', '45L', 'https://www.gregory.jp/'),
    ('GREGORY', 'Focal 48', 'フォーカル 48', 'backpack', 'backpack', '48L', 'https://www.gregory.jp/'),
    ('LA SPORTIVA', 'TX5 Evo GTX', 'TX5 Evo GTX', 'clothing', 'footwear', null, 'https://www.sportivajapan.com/'),
    ('LA SPORTIVA', 'TX5 Evo Mid GTX', 'TX5 Evo Mid GTX', 'clothing', 'footwear', null, 'https://www.sportivajapan.com/'),
    ('LA SPORTIVA', 'TX4 Evo GTX', 'TX4 Evo GTX', 'clothing', 'footwear', null, 'https://www.sportivajapan.com/'),
    ('LA SPORTIVA', 'TX4 Evo Mid GTX', 'TX4 Evo Mid GTX', 'clothing', 'footwear', null, 'https://www.sportivajapan.com/'),
    ('LA SPORTIVA', 'Ultra Raptor 3 GTX', 'Ultra Raptor 3 GTX', 'clothing', 'footwear', null, 'https://www.sportivajapan.com/'),
    ('LA SPORTIVA', 'Ultra Raptor 3 Mid GTX', 'Ultra Raptor 3 Mid GTX', 'clothing', 'footwear', null, 'https://www.sportivajapan.com/'),
    ('LA SPORTIVA', 'Aequilibrium ST GTX', 'Aequilibrium ST GTX', 'clothing', 'footwear', null, 'https://www.sportivajapan.com/'),
    ('LA SPORTIVA', 'Trango Tech GTX', 'Trango Tech GTX', 'clothing', 'footwear', null, 'https://www.sportivajapan.com/'),
    ('LA SPORTIVA', 'Akasha II', 'Akasha II', 'clothing', 'footwear', null, 'https://www.sportivajapan.com/'),
    ('LA SPORTIVA', 'Prodigio', 'Prodigio', 'clothing', 'footwear', null, 'https://www.sportivajapan.com/'),
    ('Mammut', 'Lithium 20', 'リチウム 20', 'backpack', 'backpack', '20L', 'https://www.mammut.jp/'),
    ('Mammut', 'Lithium 25', 'リチウム 25', 'backpack', 'backpack', '25L', 'https://www.mammut.jp/'),
    ('Mammut', 'Lithium 30', 'リチウム 30', 'backpack', 'backpack', '30L', 'https://www.mammut.jp/'),
    ('Mammut', 'Ducan 24', 'デュカン 24', 'backpack', 'backpack', '24L', 'https://www.mammut.jp/'),
    ('Mammut', 'Ducan 30', 'デュカン 30', 'backpack', 'backpack', '30L', 'https://www.mammut.jp/'),
    ('Mammut', 'Convey Tour HS Hooded Jacket', 'コンベイ ツアー HS フーデッド ジャケット', 'clothing', 'rain_jacket', null, 'https://www.mammut.jp/'),
    ('Mammut', 'Alto Light HS Hooded Jacket', 'アルト ライト HS フーデッド ジャケット', 'clothing', 'rain_jacket', null, 'https://www.mammut.jp/'),
    ('Mammut', 'Aconcagua ML Jacket', 'アコンカグア ML ジャケット', 'clothing', 'insulation', null, 'https://www.mammut.jp/'),
    ('Mammut', 'Runbold Pants', 'ランボールド パンツ', 'clothing', 'base_layer', null, 'https://www.mammut.jp/'),
    ('Mammut', 'Sertig II Mid GTX', 'セルティグ II ミッド GTX', 'clothing', 'footwear', null, 'https://www.mammut.jp/')
) as v(brand, model, name_ja, category_en, subcategory_en, volume, official_url)
join public.gear_categories c on c.name_en = v.category_en
join public.gear_subcategories s on s.category_id = c.id and s.name_en = v.subcategory_en
on conflict (brand, model) do update
set name_ja = excluded.name_ja,
    category_id = excluded.category_id,
    subcategory_id = excluded.subcategory_id,
    volume = excluded.volume,
    official_url = excluded.official_url,
    msrp_source_url = excluded.msrp_source_url,
    discontinued = false,
    verification_status = case
      when public.gear_products.verification_status = 'verified' then public.gear_products.verification_status
      else excluded.verification_status
    end;

insert into public.gear_product_aliases (product_id, alias)
select p.id, v.alias
from (
  values
    ('Columbia', 'Saber Five Mid Outdry', 'セイバー5ミッド'),
    ('Columbia', 'Saber Five Low Outdry', 'セイバー5ロウ'),
    ('Columbia', 'Peakfreak II Outdry', 'ピークフリーク2'),
    ('Columbia', 'Hazy Journey Waterproof', 'ヘイジージャーニー'),
    ('Columbia', 'Wabash Jacket', 'ワバシュ'),
    ('Columbia', 'Light Canyon Softshell', 'ライトキャニオン'),
    ('Columbia', 'Vizzavona Pass Jacket', 'ヴィザボナパス'),
    ('Columbia', 'Mountains Are Calling Jacket', 'マウンテンズアーコーリング'),
    ('Columbia', 'Blue Ridge Mountain 30L', 'ブルーリッジマウンテン'),
    ('Columbia', 'Castle Rock 25L', 'キャッスルロック'),
    ('MILLET', 'SAAS FEE NX 30+5', 'サースフェー30+5'),
    ('MILLET', 'SAAS FEE NX 40+5', 'サースフェー40+5'),
    ('MILLET', 'KULA 30', 'クーラ30'),
    ('MILLET', 'WELKIN 30', 'ウェルキン30'),
    ('MILLET', 'TYPHON 50000 Stretch Jacket', 'ティフォン50000ジャケット'),
    ('MILLET', 'TYPHON 50000 Stretch Pants', 'ティフォン50000パンツ'),
    ('MILLET', 'Drynamic Mesh NS', 'ドライナミックメッシュ'),
    ('MILLET', 'Drynamic Mesh 3/4 Tights', 'ドライナミックタイツ'),
    ('MILLET', 'Breathe Barrier Toi Alpha Direct Jacket', 'ブリーズバリヤーアルファ'),
    ('MILLET', 'Wanaka Stretch Pants', 'ワナカパンツ'),
    ('Arc''teryx', 'Beta Jacket', 'ベータジャケット'),
    ('Arc''teryx', 'Beta AR Jacket', 'ベータ AR'),
    ('Arc''teryx', 'Alpha SV Jacket', 'アルファ SV'),
    ('Arc''teryx', 'Atom Hoody', 'アトムフーディ'),
    ('Arc''teryx', 'Proton Hoody', 'プロトンフーディ'),
    ('Arc''teryx', 'Cerium Hoody', 'セリウムフーディ'),
    ('Arc''teryx', 'Kyanite Hoody', 'カイヤナイトフーディ'),
    ('Arc''teryx', 'Gamma Pant', 'ガンマパンツ'),
    ('Arc''teryx', 'Aerios FL 2 GTX', 'エアリオス FL 2 GTX'),
    ('Arc''teryx', 'Bora 65', 'ボラ65'),
    ('patagonia', 'Torrentshell 3L Jacket', 'トレントシェルジャケット'),
    ('patagonia', 'Torrentshell 3L Pants', 'トレントシェルパンツ'),
    ('patagonia', 'Houdini Jacket', 'フーディニ'),
    ('patagonia', 'R1 Air Zip-Neck', 'R1エアジップネック'),
    ('patagonia', 'R1 Air Hoody', 'R1エアフーディ'),
    ('patagonia', 'Nano Puff Jacket', 'ナノパフ'),
    ('patagonia', 'Down Sweater Hoody', 'ダウンセーター'),
    ('patagonia', 'Capilene Cool Daily Shirt', 'キャプリーンクールデイリー'),
    ('patagonia', 'Terrebonne Joggers', 'テルボンヌ'),
    ('patagonia', 'Black Hole Pack 32L', 'ブラックホール32L'),
    ('GREGORY', 'Zulu 30', 'ズール30'),
    ('GREGORY', 'Zulu 35', 'ズール35'),
    ('GREGORY', 'Zulu 45', 'ズール45'),
    ('GREGORY', 'Jade 28', 'ジェイド28'),
    ('GREGORY', 'Jade 38', 'ジェイド38'),
    ('GREGORY', 'Baltoro 65', 'バルトロ65'),
    ('GREGORY', 'Deva 60', 'ディバ60'),
    ('GREGORY', 'Paragon 48', 'パラゴン48'),
    ('GREGORY', 'Maven 45', 'メイブン45'),
    ('GREGORY', 'Focal 48', 'フォーカル48'),
    ('LA SPORTIVA', 'TX5 Evo GTX', 'TX5 エボ GTX'),
    ('LA SPORTIVA', 'TX5 Evo Mid GTX', 'TX5 エボ ミッド GTX'),
    ('LA SPORTIVA', 'TX4 Evo GTX', 'TX4 エボ GTX'),
    ('LA SPORTIVA', 'TX4 Evo Mid GTX', 'TX4 エボ ミッド GTX'),
    ('LA SPORTIVA', 'Ultra Raptor 3 GTX', 'ウルトララプター3 GTX'),
    ('LA SPORTIVA', 'Ultra Raptor 3 Mid GTX', 'ウルトララプター3 ミッド GTX'),
    ('LA SPORTIVA', 'Aequilibrium ST GTX', 'エクイリビウム ST GTX'),
    ('LA SPORTIVA', 'Trango Tech GTX', 'トランゴ テック GTX'),
    ('LA SPORTIVA', 'Akasha II', 'アカシャ II'),
    ('LA SPORTIVA', 'Prodigio', 'プロディジオ'),
    ('Mammut', 'Lithium 20', 'リチウム20'),
    ('Mammut', 'Lithium 25', 'リチウム25'),
    ('Mammut', 'Lithium 30', 'リチウム30'),
    ('Mammut', 'Ducan 24', 'デュカン24'),
    ('Mammut', 'Ducan 30', 'デュカン30'),
    ('Mammut', 'Convey Tour HS Hooded Jacket', 'コンベイツアーHS'),
    ('Mammut', 'Alto Light HS Hooded Jacket', 'アルトライトHS'),
    ('Mammut', 'Aconcagua ML Jacket', 'アコンカグア'),
    ('Mammut', 'Runbold Pants', 'ランボールド'),
    ('Mammut', 'Sertig II Mid GTX', 'セルティグIIミッド')
) as v(brand, model, alias)
join public.gear_products p on p.brand = v.brand and p.model = v.model
where not exists (
  select 1
  from public.gear_product_aliases existing
  where lower(existing.alias) = lower(v.alias)
);
