insert into public.gear_products (
  brand,
  model,
  name_ja,
  category_id,
  subcategory_id,
  weight_grams,
  official_weight_grams,
  measured_weight_grams,
  msrp_jpy,
  size,
  volume,
  color,
  material,
  capacity,
  official_url,
  image_url,
  released_at,
  discontinued,
  msrp_source_url,
  last_verified_at,
  verification_status
)
select
  v.brand,
  v.model,
  v.name_ja,
  c.id,
  s.id,
  v.official_weight_grams,
  v.official_weight_grams,
  null,
  v.msrp_jpy,
  v.size,
  v.volume,
  null,
  null,
  v.capacity,
  v.official_url,
  v.image_url,
  null,
  false,
  v.official_url,
  date '2026-06-21',
  'verified'
from (
  values
    (
      'GREGORY',
      'Zulu 35',
      'ズール35',
      'backpack',
      'backpack',
      1490,
      33000,
      'M/L',
      '35L',
      '35 L',
      'https://item.rakuten.co.jp/gregory-japan/l24-9976/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/l24-9976/l24-9976.jpg'
    ),
    (
      'GREGORY',
      'Zulu 45',
      'ズール45',
      'backpack',
      'backpack',
      1590,
      35200,
      'M/L',
      '45L',
      '45 L',
      'https://item.rakuten.co.jp/gregory-japan/l25-0662/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/l25-0662/l25-0662.jpg'
    ),
    (
      'GREGORY',
      'Jade 28',
      'ジェイド28',
      'backpack',
      'backpack',
      1240,
      28600,
      'XS/S',
      '28L',
      '28 L',
      'https://item.rakuten.co.jp/gregory-japan/m75-a257/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/m75-a257/m75-a257.jpg'
    ),
    (
      'GREGORY',
      'Jade 33',
      'ジェイド33',
      'backpack',
      'backpack',
      1360,
      33000,
      'XS/S',
      '33L',
      '33 L',
      'https://item.rakuten.co.jp/gregory-japan/44j-341/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/13233065/imgrc0113836093.jpg'
    ),
    (
      'GREGORY',
      'Jade 43',
      'ジェイド43',
      'backpack',
      'backpack',
      1480,
      35200,
      'XS/S',
      '43L',
      '43 L',
      'https://item.rakuten.co.jp/gregory-japan/44j-340/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/13233322/imgrc0113835616.jpg'
    ),
    (
      'GREGORY',
      'Stout 35',
      'スタウト35',
      'backpack',
      'backpack',
      1220,
      30800,
      null,
      '35L',
      '35 L',
      'https://item.rakuten.co.jp/gregory-japan/n22-a266/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/n22-a266/n22-a266.jpg'
    ),
    (
      'GREGORY',
      'Amber 34',
      'アンバー34',
      'backpack',
      'backpack',
      1210,
      30800,
      null,
      '34L',
      '34 L',
      'https://item.rakuten.co.jp/gregory-japan/n26-6059/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/n26-6059/n26-6059.jpg'
    ),
    (
      'GREGORY',
      'Citro 24',
      'シトロ24',
      'backpack',
      'backpack',
      930,
      24200,
      null,
      '24L',
      '24 L',
      'https://item.rakuten.co.jp/gregory-japan/j78-7416/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/j78-7416/j78-7416.jpg'
    ),
    (
      'GREGORY',
      'Juno 24',
      'ジュノ24',
      'backpack',
      'backpack',
      890,
      24200,
      null,
      '24L',
      '24 L',
      'https://item.rakuten.co.jp/gregory-japan/j80-1327/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/j80-1327/j80-1327.jpg'
    ),
    (
      'GREGORY',
      'Miko 25',
      'ミコ25',
      'backpack',
      'backpack',
      980,
      26400,
      null,
      '25L',
      '25 L',
      'https://item.rakuten.co.jp/gregory-japan/l51-9968/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/l51-9968/l51-9968.jpg'
    ),
    (
      'GREGORY',
      'Maya 20',
      'マヤ20',
      'backpack',
      'backpack',
      840,
      24200,
      null,
      '20L',
      '20 L',
      'https://item.rakuten.co.jp/gregory-japan/l56-5586/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/l56-5586/l56-5586.jpg'
    ),
    (
      'GREGORY',
      'Maya 25',
      'マヤ25',
      'backpack',
      'backpack',
      910,
      26400,
      null,
      '25L',
      '25 L',
      'https://item.rakuten.co.jp/gregory-japan/l55-9975/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/l55-9975/l55-9975.jpg'
    ),
    (
      'GREGORY',
      'Nano 18',
      'ナノ18',
      'backpack',
      'backpack',
      499,
      12100,
      null,
      '18L',
      '18 L',
      'https://item.rakuten.co.jp/gregory-japan/43j-029/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/11968959/imgrc0115351658.jpg'
    ),
    (
      'GREGORY',
      'Arrio 24',
      'アリオ24',
      'backpack',
      'backpack',
      767,
      24200,
      null,
      '24L',
      '24 L',
      'https://item.rakuten.co.jp/gregory-japan/54j-008/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/13063296/1.jpg'
    ),
    (
      'GREGORY',
      'Arrio 28',
      'アリオ28',
      'backpack',
      'backpack',
      817,
      26400,
      null,
      '28L',
      '28 L',
      'https://item.rakuten.co.jp/gregory-japan/54j-009/',
      'https://image.rakuten.co.jp/gregory-japan/cabinet/13062555/1.jpg'
    )
) as v(
  brand,
  model,
  name_ja,
  category_en,
  subcategory_en,
  official_weight_grams,
  msrp_jpy,
  size,
  volume,
  capacity,
  official_url,
  image_url
)
join public.gear_categories c on c.name_en = v.category_en
join public.gear_subcategories s on s.category_id = c.id and s.name_en = v.subcategory_en
on conflict (brand, model) do update
set name_ja = excluded.name_ja,
    category_id = excluded.category_id,
    subcategory_id = excluded.subcategory_id,
    weight_grams = excluded.weight_grams,
    official_weight_grams = excluded.official_weight_grams,
    measured_weight_grams = null,
    msrp_jpy = excluded.msrp_jpy,
    size = excluded.size,
    volume = excluded.volume,
    capacity = excluded.capacity,
    official_url = excluded.official_url,
    image_url = excluded.image_url,
    msrp_source_url = excluded.official_url,
    last_verified_at = excluded.last_verified_at,
    verification_status = 'verified',
    discontinued = false;

insert into public.gear_product_aliases (product_id, alias)
select p.id, v.alias
from (
  values
    ('GREGORY', 'Zulu 35', 'ズール35'),
    ('GREGORY', 'Zulu 35', 'ZULU35'),
    ('GREGORY', 'Zulu 45', 'ズール45'),
    ('GREGORY', 'Zulu 45', 'ZULU45'),
    ('GREGORY', 'Jade 28', 'ジェイド28'),
    ('GREGORY', 'Jade 28', 'JADE28'),
    ('GREGORY', 'Jade 33', 'ジェイド33'),
    ('GREGORY', 'Jade 33', 'JADE33'),
    ('GREGORY', 'Jade 43', 'ジェイド43'),
    ('GREGORY', 'Jade 43', 'JADE43'),
    ('GREGORY', 'Stout 35', 'スタウト35'),
    ('GREGORY', 'Stout 35', 'STOUT35'),
    ('GREGORY', 'Amber 34', 'アンバー34'),
    ('GREGORY', 'Amber 34', 'AMBER34'),
    ('GREGORY', 'Citro 24', 'シトロ24'),
    ('GREGORY', 'Citro 24', 'CITRO24'),
    ('GREGORY', 'Juno 24', 'ジュノ24'),
    ('GREGORY', 'Juno 24', 'JUNO24'),
    ('GREGORY', 'Miko 25', 'ミコ25'),
    ('GREGORY', 'Miko 25', 'MIKO25'),
    ('GREGORY', 'Maya 20', 'マヤ20'),
    ('GREGORY', 'Maya 20', 'MAYA20'),
    ('GREGORY', 'Maya 25', 'マヤ25'),
    ('GREGORY', 'Maya 25', 'MAYA25'),
    ('GREGORY', 'Nano 18', 'ナノ18'),
    ('GREGORY', 'Nano 18', 'NANO18'),
    ('GREGORY', 'Arrio 24', 'アリオ24'),
    ('GREGORY', 'Arrio 24', 'ARRIO24'),
    ('GREGORY', 'Arrio 28', 'アリオ28'),
    ('GREGORY', 'Arrio 28', 'ARRIO28')
) as v(brand, model, alias)
join public.gear_products p on p.brand = v.brand and p.model = v.model
where not exists (
  select 1
  from public.gear_product_aliases existing
  where lower(existing.alias) = lower(v.alias)
);
